import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import {
  assertMigrationTestTarget,
  buildPostgresqlSchema,
  createSqliteMigrationSnapshot,
  encodePostgresqlMigrationValue,
  inspectSqliteSchema,
  normalizeMigrationValue,
  openReadOnlySqliteSnapshot,
  readNormalizedTableRows,
  tableDigests,
  topologicalTableOrder,
} from "../lib/postgresql/sqlite-migration.mjs";

const PARENT_ID = "11111111-1111-4111-8111-111111111111";

function createFixture(database) {
  database.exec(`PRAGMA foreign_keys=ON;
    CREATE TABLE parent_records (
      id TEXT PRIMARY KEY,
      metadata_json TEXT NOT NULL DEFAULT '{}',
      observed_at TEXT NOT NULL,
      code TEXT NOT NULL UNIQUE
    );
    CREATE TABLE child_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      parent_id TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
      file_size INTEGER NOT NULL DEFAULT 0 CHECK (file_size >= 0),
      payment_date TEXT,
      FOREIGN KEY (parent_id) REFERENCES parent_records(id) ON DELETE CASCADE
    );
    CREATE INDEX idx_child_records_enabled ON child_records(enabled) WHERE enabled = 1;
    INSERT INTO parent_records(id,metadata_json,observed_at,code)
      VALUES ('${PARENT_ID}','{"b":2,"a":1}','2026-07-20 08:09:10','alpha');
    INSERT INTO child_records(parent_id,enabled,file_size,payment_date)
      VALUES ('${PARENT_ID}',1,42,'2026-07-20');`);
}

test("SQLite schema conversion produces native PostgreSQL types and constraints", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    const source = inspectSqliteSchema(database);
    const generated = buildPostgresqlSchema(source, { schema: "app" });
    assert.equal(source.tableCount, 2);
    assert.match(generated.sql, /"id" uuid/);
    assert.match(generated.sql, /"metadata_json" jsonb/);
    assert.match(generated.sql, /"observed_at" timestamptz/);
    assert.match(generated.sql, /GENERATED BY DEFAULT AS IDENTITY/);
    assert.match(generated.sql, /"enabled" boolean NOT NULL DEFAULT TRUE/);
    assert.match(generated.sql, /"enabled" IN \(FALSE, TRUE\)/);
    assert.match(generated.sql, /FOREIGN KEY \("parent_id"\)/);
    assert.match(generated.sql, /CREATE INDEX "idx_child_records_enabled"/);
    assert.deepEqual(topologicalTableOrder(source), ["parent_records", "child_records"]);
  } finally {
    database.close();
  }
});

test("migration normalization gives SQLite and PostgreSQL-shaped rows equal hashes", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    const source = inspectSqliteSchema(database);
    const parent = source.tables.find((table) => table.name === "parent_records");
    const sqliteRows = readNormalizedTableRows(database, parent);
    const postgresqlRow = {
      id: PARENT_ID.toUpperCase(),
      metadata_json: { a: 1, b: 2 },
      observed_at: new Date("2026-07-20T08:09:10.000Z"),
      code: "alpha",
    };
    assert.deepEqual(tableDigests(sqliteRows, parent), tableDigests([postgresqlRow], parent));
    const dateColumn = source.tables.find((table) => table.name === "child_records").columns.find((column) => column.name === "payment_date");
    assert.equal(normalizeMigrationValue("2026-07-20", dateColumn), "2026-07-20");
    assert.equal(normalizeMigrationValue(new Date(2026, 6, 20), dateColumn), "2026-07-20");
    const timestampColumn = parent.columns.find((column) => column.name === "observed_at");
    assert.equal(normalizeMigrationValue(new Date("2026-07-20T08:09:10.123Z"), timestampColumn), "2026-07-20T08:09:10.123Z");
  } finally {
    database.close();
  }
});

test("PostgreSQL JSON parameters are encoded as JSON rather than PostgreSQL arrays", () => {
  const column = { name: "scopes_json", logicalType: "json" };
  assert.equal(encodePostgresqlMigrationValue('["main","ads"]', column), '["main","ads"]');
  assert.equal(encodePostgresqlMigrationValue({ b: 2, a: 1 }, column), '{"a":1,"b":2}');
});

test("official SQLite backup creates a consistent read-only migration source", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "f3-snapshot-test-"));
  const sourcePath = path.join(root, "source.sqlite");
  const snapshotPath = path.join(root, "snapshot.sqlite");
  const database = new DatabaseSync(sourcePath);
  createFixture(database);
  database.close();
  try {
    const result = await createSqliteMigrationSnapshot({ sourcePath, destinationPath: snapshotPath });
    assert.equal(result.integrity, "ok");
    assert.equal(result.foreignKeyViolations, 0);
    assert.equal(result.readOnly, true);
    assert.match(result.snapshotHash, /^[0-9a-f]{64}$/);
    const snapshot = openReadOnlySqliteSnapshot(snapshotPath);
    try {
      assert.equal(snapshot.prepare("SELECT count(*) count FROM child_records").get().count, 1);
      assert.throws(() => snapshot.exec("DELETE FROM child_records"));
    } finally {
      snapshot.close();
    }
  } finally {
    try { await fs.chmod(snapshotPath, 0o600); } catch {}
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("F3 target guard rejects production and shared database targets", () => {
  const config = { database: "commerce_ops", testDatabase: "commerce_ops_migration_test" };
  assert.doesNotThrow(() => assertMigrationTestTarget(config, { database: "commerce_ops_migration_test" }));
  assert.throws(() => assertMigrationTestTarget(config, { database: "commerce_ops" }), /only write/);
  assert.throws(() => assertMigrationTestTarget({ database: "same", testDatabase: "same" }, { database: "same" }), /only write/);
});

test("F3 runner never constructs a production PostgreSQL provider", async () => {
  const source = await fs.readFile(path.resolve("scripts/postgresql-f3-migration-test.mjs"), "utf8");
  assert.match(source, /createPostgresqlProvider\(config, \{ database: "test", role: "migrator" \}\)/);
  assert.doesNotMatch(source, /createPostgresqlProvider\([^\n]+database:\s*"production"/);
  assert.doesNotMatch(source, /DATABASE_PROVIDER\s*=\s*postgres/i);
  assert.doesNotMatch(source, /DROP SCHEMA/i);
});
