import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import {
  assertMigrationTestTarget,
  buildPostgresqlSchema,
  createTableDigestAccumulator,
  createSqliteMigrationSnapshot,
  encodeNormalizedPostgresqlMigrationValue,
  encodePostgresqlMigrationValue,
  inspectSqliteSchema,
  normalizeMigrationValue,
  normalizePostgresqlMigrationValue,
  openReadOnlySqliteSnapshot,
  readNormalizedTableBatches,
  readNormalizedTableRows,
  tableBatchInsertSql,
  tableDigests,
  topologicalTableOrder,
} from "../lib/postgresql/sqlite-migration.mjs";
import {
  assertF3ExecutionApproval,
  resolveF3BatchRows,
} from "../scripts/postgresql-f3-migration-test.mjs";

const PARENT_ID = "11111111-1111-4111-8111-111111111111";

function createFixture(database) {
  database.exec(`PRAGMA foreign_keys=ON;
    CREATE TABLE parent_records (
      id TEXT PRIMARY KEY,
      metadata_json TEXT NOT NULL DEFAULT '{}',
      observed_at TEXT NOT NULL,
      code TEXT NOT NULL UNIQUE
    );
    CREATE TABLE child_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      parent_id TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
      is_current INTEGER NOT NULL DEFAULT 0 CHECK (is_current IN (0, 1)),
      file_size INTEGER NOT NULL DEFAULT 0 CHECK (file_size >= 0),
      payment_date TEXT,
      FOREIGN KEY (parent_id) REFERENCES parent_records(id) ON DELETE CASCADE
    );
    CREATE INDEX idx_child_records_enabled ON child_records(enabled) WHERE enabled = 1;
    INSERT INTO parent_records(id,metadata_json,observed_at,code)
      VALUES ('${PARENT_ID}','{"b":2,"a":1}','2026-07-20 08:09:10','alpha');
    INSERT INTO child_records(parent_id,enabled,file_size,payment_date)
      VALUES ('${PARENT_ID}',1,42,'2026-07-20');`);
}

test("SQLite schema conversion produces native PostgreSQL types and constraints", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    const source = inspectSqliteSchema(database);
    const generated = buildPostgresqlSchema(source, { schema: "app" });
    assert.equal(source.tableCount, 2);
    assert.match(generated.sql, /"id" uuid/);
    assert.match(generated.sql, /"metadata_json" jsonb/);
    assert.match(generated.sql, /"observed_at" timestamptz/);
    assert.match(generated.sql, /GENERATED BY DEFAULT AS IDENTITY/);
    assert.match(generated.sql, /"enabled" boolean NOT NULL DEFAULT TRUE/);
    assert.match(generated.sql, /"enabled" IN \(FALSE, TRUE\)/);
    assert.match(generated.sql, /"is_current" boolean NOT NULL DEFAULT FALSE/);
    assert.match(generated.sql, /"is_current" IN \(FALSE, TRUE\)/);
    assert.match(generated.sql, /FOREIGN KEY \("parent_id"\)/);
    assert.match(generated.sql, /CREATE INDEX "idx_child_records_enabled"/);
    assert.deepEqual(topologicalTableOrder(source), ["parent_records", "child_records"]);
  } finally {
    database.close();
  }
});

test("current Price Control expression index and SQLite views convert to PostgreSQL", () => {
  const database = new DatabaseSync(":memory:");
  try {
    database.exec(`
      CREATE TABLE price_control_sync_runs (
        id TEXT PRIMARY KEY,
        status TEXT NOT NULL
      );
      CREATE UNIQUE INDEX uq_price_control_one_running_sync
        ON price_control_sync_runs((1)) WHERE status='RUNNING';
      CREATE VIEW running_price_control_syncs_v AS
        SELECT id,status FROM price_control_sync_runs WHERE status='RUNNING';
    `);
    const source = inspectSqliteSchema(database);
    const generated = buildPostgresqlSchema(source, { schema: "app" });
    assert.equal(source.viewCount, 1);
    assert.equal(generated.expectedViewCount, 1);
    assert.match(
      generated.sql,
      /CREATE UNIQUE INDEX "uq_price_control_one_running_sync" ON "app"\."price_control_sync_runs" \(\(1\)\) WHERE status='RUNNING'/,
    );
    assert.match(generated.sql, /CREATE VIEW "app"\."running_price_control_syncs_v" AS/);
  } finally {
    database.close();
  }
});

test("external and correlation identifiers remain text instead of being guessed as UUIDs", () => {
  const database = new DatabaseSync(":memory:");
  try {
    database.exec(`CREATE TABLE external_identifiers (
      id TEXT PRIMARY KEY,
      request_id TEXT,
      shop_id TEXT,
      platform_category_id TEXT,
      platform_product_id TEXT,
      platform_listing_id TEXT
    );`);
    const source = inspectSqliteSchema(database);
    const table = source.tables.find((item) => item.name === "external_identifiers");
    assert.equal(table.columns.find((item) => item.name === "id").logicalType, "uuid");
    for (const name of ["request_id", "shop_id", "platform_category_id", "platform_product_id", "platform_listing_id"]) {
      assert.equal(table.columns.find((item) => item.name === name).logicalType, "text");
    }
  } finally { database.close(); }
});

test("F3 data-aware UUID inference preserves non-UUID business identifiers and foreign keys as text", () => {
  const database = new DatabaseSync(":memory:");
  try {
    database.exec(`
      PRAGMA foreign_keys=ON;
      CREATE TABLE business_accounts (id TEXT PRIMARY KEY);
      CREATE TABLE business_events (
        id TEXT PRIMARY KEY,
        account_id TEXT NOT NULL REFERENCES business_accounts(id)
      );
      INSERT INTO business_accounts(id) VALUES ('account:platform:shop-01');
      INSERT INTO business_events(id,account_id)
        VALUES ('event:daily:2026-08-06','account:platform:shop-01');
    `);
    const source = inspectSqliteSchema(database, { verifyUuidValues: true });
    const account = source.tables.find((table) => table.name === "business_accounts");
    const event = source.tables.find((table) => table.name === "business_events");
    assert.equal(account.columns.find((column) => column.name === "id").logicalType, "text");
    assert.equal(event.columns.find((column) => column.name === "id").logicalType, "text");
    assert.equal(event.columns.find((column) => column.name === "account_id").logicalType, "text");
    const generated = buildPostgresqlSchema(source, { schema: "app" });
    assert.match(generated.sql, /"account_id" text NOT NULL/);
    assert.match(generated.sql, /FOREIGN KEY \("account_id"\).*"business_accounts" \("id"\)/s);
  } finally {
    database.close();
  }
});

test("migration normalization gives SQLite and PostgreSQL-shaped rows equal hashes", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    const source = inspectSqliteSchema(database);
    const parent = source.tables.find((table) => table.name === "parent_records");
    const sqliteRows = readNormalizedTableRows(database, parent);
    const postgresqlRow = {
      id: PARENT_ID.toUpperCase(),
      metadata_json: { a: 1, b: 2 },
      observed_at: new Date("2026-07-20T08:09:10.000Z"),
      code: "alpha",
    };
    assert.deepEqual(tableDigests(sqliteRows, parent), tableDigests([postgresqlRow], parent));
    const dateColumn = source.tables.find((table) => table.name === "child_records").columns.find((column) => column.name === "payment_date");
    assert.equal(normalizeMigrationValue("2026-07-20", dateColumn), "2026-07-20");
    assert.equal(normalizeMigrationValue(new Date(2026, 6, 20), dateColumn), "2026-07-20");
    const timestampColumn = parent.columns.find((column) => column.name === "observed_at");
    assert.equal(normalizeMigrationValue(new Date("2026-07-20T08:09:10.123Z"), timestampColumn), "2026-07-20T08:09:10.123Z");
  } finally {
    database.close();
  }
});

test("PostgreSQL JSON parameters are encoded as JSON rather than PostgreSQL arrays", () => {
  const column = { name: "scopes_json", logicalType: "json" };
  assert.equal(encodePostgresqlMigrationValue('["main","ads"]', column), '["main","ads"]');
  assert.equal(encodePostgresqlMigrationValue({ b: 2, a: 1 }, column), '{"a":1,"b":2}');
  assert.equal(encodeNormalizedPostgresqlMigrationValue("人工商品名", column), '"人工商品名"');
  assert.equal(normalizePostgresqlMigrationValue("人工商品名", column), "人工商品名");
  assert.deepEqual(normalizePostgresqlMigrationValue({ b: 2, a: 1 }, column), { a: 1, b: 2 });
});

test("already-normalized JSON scalar rows can be hashed without a second parse", () => {
  const table = {
    columns: [
      { name: "id", logicalType: "integer", pk: true },
      { name: "next_value_json", logicalType: "json", pk: false },
    ],
  };
  const rows = [{ id: 1, next_value_json: "人工商品名" }];
  const digest = tableDigests(rows, table, { valuesAreNormalized: true });
  assert.match(digest.full, /^[0-9a-f]{64}$/);
  assert.match(digest.keys, /^[0-9a-f]{64}$/);
});

test("streaming SQLite migration reads bounded normalized batches", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    database.exec(`INSERT INTO parent_records(id,metadata_json,observed_at,code)
      VALUES ('22222222-2222-4222-8222-222222222222','{"z":3}','2026-07-21 00:00:00','beta')`);
    const table = inspectSqliteSchema(database).tables.find((item) => item.name === "parent_records");
    const batches = [...readNormalizedTableBatches(database, table, { batchSize: 1 })];
    assert.deepEqual(batches.map((batch) => batch.length), [1, 1]);
    assert.deepEqual(batches.flat(), readNormalizedTableRows(database, table));
    assert.throws(() => [...readNormalizedTableBatches(database, table, { batchSize: 0 })], /positive integer/);
  } finally {
    database.close();
  }
});

test("streaming table digests are order independent and duplicate sensitive", () => {
  const database = new DatabaseSync(":memory:");
  try {
    createFixture(database);
    database.exec(`INSERT INTO parent_records(id,metadata_json,observed_at,code)
      VALUES ('22222222-2222-4222-8222-222222222222','{"z":3}','2026-07-21 00:00:00','beta')`);
    const table = inspectSqliteSchema(database).tables.find((item) => item.name === "parent_records");
    const rows = readNormalizedTableRows(database, table);
    const forward = createTableDigestAccumulator(table, { valuesAreNormalized: true });
    const reverse = createTableDigestAccumulator(table, { valuesAreNormalized: true });
    const duplicate = createTableDigestAccumulator(table, { valuesAreNormalized: true });
    forward.addMany(rows);
    reverse.addMany([...rows].reverse());
    duplicate.addMany([...rows, rows[0]]);
    assert.deepEqual(forward.finish(), reverse.finish());
    assert.notEqual(forward.finish().full, duplicate.finish().full);
    assert.equal(forward.finish().rowCount, 2);
    assert.equal(duplicate.finish().rowCount, 3);
  } finally {
    database.close();
  }
});

test("F3 batch inserts stay below PostgreSQL bind limits", () => {
  const provider = { placeholder: (index) => `$${index}` };
  const table = { name: "sample_rows", columns: [{ name: "id" }, { name: "value" }] };
  assert.equal(
    tableBatchInsertSql("app", table, provider, 2),
    'INSERT INTO "app"."sample_rows" ("id", "value") VALUES ($1, $2), ($3, $4)',
  );
  assert.equal(resolveF3BatchRows(undefined, 10), 250);
  assert.equal(resolveF3BatchRows(5_000, 100), 600);
  assert.throws(() => resolveF3BatchRows(0, 10), /between 1 and 5000/);
});

test("F3 destructive migration requires an exact test-database confirmation", () => {
  const config = { testDatabase: "commerce_ops_migration_test" };
  assert.throws(() => assertF3ExecutionApproval({}, config), /--apply --confirm-database/);
  assert.throws(
    () => assertF3ExecutionApproval({ apply: true, confirmedDatabase: "commerce_ops" }, config),
    /commerce_ops_migration_test/,
  );
  assert.doesNotThrow(() => assertF3ExecutionApproval({
    apply: true,
    confirmedDatabase: "commerce_ops_migration_test",
  }, config));
});

test("official SQLite backup creates a consistent read-only migration source", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "f3-snapshot-test-"));
  const sourcePath = path.join(root, "source.sqlite");
  const snapshotPath = path.join(root, "snapshot.sqlite");
  const database = new DatabaseSync(sourcePath);
  createFixture(database);
  database.close();
  try {
    const result = await createSqliteMigrationSnapshot({ sourcePath, destinationPath: snapshotPath });
    assert.equal(result.integrity, "ok");
    assert.equal(result.foreignKeyViolations, 0);
    assert.equal(result.readOnly, true);
    assert.match(result.snapshotHash, /^[0-9a-f]{64}$/);
    const snapshot = openReadOnlySqliteSnapshot(snapshotPath);
    try {
      assert.equal(snapshot.prepare("SELECT count(*) count FROM child_records").get().count, 1);
      assert.throws(() => snapshot.exec("DELETE FROM child_records"));
    } finally {
      snapshot.close();
    }
  } finally {
    try { await fs.chmod(snapshotPath, 0o600); } catch {}
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("F3 target guard rejects production and shared database targets", () => {
  const config = { database: "commerce_ops", testDatabase: "commerce_ops_migration_test" };
  assert.doesNotThrow(() => assertMigrationTestTarget(config, { database: "commerce_ops_migration_test" }));
  assert.throws(() => assertMigrationTestTarget(config, { database: "commerce_ops" }), /only write/);
  assert.throws(() => assertMigrationTestTarget({ database: "same", testDatabase: "same" }, { database: "same" }), /only write/);
});

test("F3 runner never constructs a production PostgreSQL provider", async () => {
  const source = await fs.readFile(path.resolve("scripts/postgresql-f3-migration-test.mjs"), "utf8");
  assert.match(source, /createPostgresqlProvider\(config, \{ database: "test", role: "migrator" \}\)/);
  assert.doesNotMatch(source, /createPostgresqlProvider\([^\n]+database:\s*"production"/);
  assert.doesNotMatch(source, /DATABASE_PROVIDER\s*=\s*postgres/i);
  assert.doesNotMatch(source, /DROP SCHEMA/i);
  assert.match(source, /readNormalizedTableBatches/);
  assert.match(source, /tableBatchInsertSql/);
  assert.match(source, /DECLARE f3_validation_cursor NO SCROLL CURSOR/);
  assert.doesNotMatch(source, /readNormalizedTableRows/);
});
