CREATE TABLE "app"."dingtalk_robot_configs" (
  "id" text,
  "name" text NOT NULL,
  "encrypted_webhook_url" text NOT NULL,
  "encrypted_secret" text,
  "enabled" integer NOT NULL DEFAULT 1,
  "notify_on_success" integer NOT NULL DEFAULT 1,
  "notify_on_failure" integer NOT NULL DEFAULT 1,
  "notify_on_empty" integer NOT NULL DEFAULT 1,
  "at_all" integer NOT NULL DEFAULT 0,
  "at_mobiles_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "app"."export_files" (
  "id" text,
  "file_type" text NOT NULL DEFAULT 'excel',
  "source_type" text NOT NULL,
  "task_id" text,
  "run_id" text,
  "request_key" text,
  "original_filename" text NOT NULL,
  "storage_filename" text NOT NULL,
  "relative_path" text NOT NULL,
  "mime_type" text NOT NULL DEFAULT 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  "file_size" bigint NOT NULL DEFAULT 0,
  "file_hash" text,
  "status" text NOT NULL DEFAULT 'available',
  "expires_at" timestamptz,
  "missing_at" timestamptz,
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("relative_path"),
  UNIQUE ("run_id"),
  CHECK (file_type IN ('excel')),
  CHECK (source_type IN (
      'mabang_manual_order',
      'mabang_manual_inventory',
      'mabang_scheduled_order',
      'mabang_scheduled_inventory'
    )),
  CHECK (file_size >= 0),
  CHECK (status IN ('available', 'missing', 'expired', 'deleted', 'generation_failed', 'integrity_failed'))
);

CREATE TABLE "app"."file_lifecycle_items" (
  "id" text,
  "scan_id" text NOT NULL,
  "classification" text NOT NULL,
  "categories_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "scope" text NOT NULL,
  "source_type" text,
  "file_id" text,
  "task_id" text,
  "run_id" text,
  "masked_filename" text NOT NULL,
  "file_size" bigint NOT NULL DEFAULT 0,
  "file_created_at" timestamptz,
  "file_modified_at" timestamptz,
  "database_status" text,
  "physical_status" text NOT NULL,
  "suggest_quarantine" integer NOT NULL DEFAULT 0,
  "suggest_cleanup" integer NOT NULL DEFAULT 0,
  "reason_code" text NOT NULL,
  "short_hash" text,
  "error_code" text,
  "created_at" timestamptz NOT NULL,
  "detected_file_type" text,
  "review_status" text NOT NULL DEFAULT 'pending_review',
  "reviewed_at" timestamptz,
  "reviewed_by" text,
  "review_reason" text,
  "root_key" text,
  "relative_path" text,
  "full_hash" text,
  "job_id" text,
  "mime_type" text,
  "signature_code" text,
  "detection_reason_code" text,
  "managed_file_id" text,
  "original_relative_path" text,
  "quarantine_relative_path" text,
  "quarantined_at" timestamptz,
  "restored_at" timestamptz,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  CHECK (file_size >= 0),
  CHECK (suggest_quarantine IN (0, 1)),
  CHECK (suggest_cleanup IN (0, 1)),
  CHECK (detected_file_type IS NULL OR detected_file_type IN (
    'advertising_source',
    'advertising_output',
    'advertising_report',
    'advertising_temp',
    'advertising_unknown'
  )),
  CHECK (review_status IN (
    'pending_review',
    'approved_for_registration',
    'registered',
    'approved_for_quarantine',
    'quarantined',
    'restored',
    'rejected',
    'protected'
  ))
);

CREATE TABLE "app"."file_lifecycle_protected_files" (
  "file_id" text,
  "reason" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("file_id")
);

CREATE TABLE "app"."file_lifecycle_scans" (
  "id" text,
  "status" text NOT NULL,
  "scopes_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "summary_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "scope_errors_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "total_files" integer NOT NULL DEFAULT 0,
  "total_bytes" bigint NOT NULL DEFAULT 0,
  "truncated" integer NOT NULL DEFAULT 0,
  "report_file_id" text,
  "error_code" text,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (status IN ('running', 'completed', 'failed')),
  CHECK (total_files >= 0),
  CHECK (total_bytes >= 0),
  CHECK (truncated IN (0, 1))
);

CREATE TABLE "app"."file_quarantine_records" (
  "id" text,
  "lifecycle_item_id" text NOT NULL,
  "managed_file_id" text,
  "root_key" text NOT NULL,
  "original_relative_path" text NOT NULL,
  "quarantine_relative_path" text NOT NULL,
  "file_size" bigint NOT NULL,
  "file_hash" text NOT NULL,
  "status" text NOT NULL,
  "quarantined_at" timestamptz NOT NULL,
  "quarantined_by" text NOT NULL,
  "quarantine_reason" text NOT NULL,
  "restored_at" timestamptz,
  "restored_by" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("quarantine_relative_path"),
  CHECK (file_size >= 0),
  CHECK (length(file_hash) = 64),
  CHECK (status IN ('quarantined', 'restored'))
);

CREATE TABLE "app"."foundation_account_capabilities" (
  "account_id" text,
  "capability_code" text,
  "status" text NOT NULL DEFAULT 'active',
  "config_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("account_id", "capability_code"),
  CHECK (capability_code IN (
      'orders.read',
      'inventory.read',
      'images.read',
      'listing.read',
      'listing.write'
    )),
  CHECK (status IN ('active', 'disabled', 'requires_binding'))
);

CREATE TABLE "app"."foundation_identity_links" (
  "id" text,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL,
  "source_system_code" text NOT NULL,
  "source_entity_type" text NOT NULL,
  "external_key" text NOT NULL,
  "normalized_external_key" text NOT NULL,
  "match_status" text NOT NULL DEFAULT 'confirmed',
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "first_seen_at" timestamptz NOT NULL,
  "last_seen_at" timestamptz NOT NULL,
  "confirmed_by" text,
  "confirmed_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system_code", "source_entity_type", "normalized_external_key"),
  CHECK (entity_type IN ('product', 'sku', 'store', 'warehouse', 'owner')),
  CHECK (match_status IN ('confirmed', 'suggested', 'rejected', 'unresolved'))
);

CREATE TABLE "app"."foundation_integration_accounts" (
  "id" text,
  "source_system_code" text NOT NULL,
  "display_name" text NOT NULL,
  "credential_ref_type" text NOT NULL,
  "credential_ref_id" text,
  "status" text NOT NULL DEFAULT 'active',
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_verified_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system_code", "credential_ref_type", "credential_ref_id"),
  CHECK (credential_ref_type IN (
      'mabang_account_profile',
      'sidecar_managed',
      'environment',
      'none'
    )),
  CHECK (status IN ('active', 'disabled', 'verification_required')),
  CHECK (credential_ref_type = 'none'
    OR (credential_ref_id IS NOT NULL AND credential_ref_id <> ''))
);

CREATE TABLE "app"."foundation_owners" (
  "id" text,
  "display_name" text NOT NULL,
  "source_system_code" text,
  "external_key" text,
  "status" text NOT NULL DEFAULT 'active',
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system_code", "external_key"),
  CHECK (status IN ('active', 'inactive', 'unassigned'))
);

CREATE TABLE "app"."foundation_source_runs" (
  "id" text,
  "source_system_code" text NOT NULL,
  "account_id" text,
  "domain" text NOT NULL,
  "source_ref_type" text NOT NULL,
  "source_ref_id" text NOT NULL,
  "status" text NOT NULL,
  "watermark_at" timestamptz,
  "input_fingerprint" text,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("domain", "source_ref_type", "source_ref_id"),
  CHECK (domain IN ('mabang_data', 'growth', 'images', 'listing', 'product')),
  CHECK (status IN (
      'PENDING',
      'RUNNING',
      'SUCCEEDED',
      'PARTIAL_SUCCESS',
      'FAILED',
      'CANCELLED'
    ))
);

CREATE TABLE "app"."foundation_source_systems" (
  "code" text,
  "source_type" text NOT NULL,
  "display_name" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("code"),
  CHECK (source_type IN ('erp', 'marketplace', 'internal', 'ai_provider')),
  CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE "app"."foundation_task_events" (
  "id" text,
  "task_id" text NOT NULL,
  "event_type" text NOT NULL,
  "from_state" text,
  "to_state" text NOT NULL,
  "source_state" text,
  "actor_type" text NOT NULL,
  "actor_id" text NOT NULL,
  "reason_code" text,
  "message" text,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "idempotency_key" text NOT NULL,
  "task_version" integer NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("task_id", "task_version"),
  UNIQUE ("task_id", "idempotency_key"),
  CHECK (actor_type IN ('user', 'system')),
  CHECK (task_version >= 1)
);

CREATE TABLE "app"."foundation_task_leases" (
  "task_id" text,
  "lease_owner" text NOT NULL,
  "lease_token" text NOT NULL,
  "acquired_at" timestamptz NOT NULL,
  "renewed_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("task_id"),
  UNIQUE ("lease_token"),
  CHECK (expires_at > renewed_at)
);

CREATE TABLE "app"."foundation_tasks" (
  "id" text,
  "domain" text NOT NULL,
  "task_kind" text NOT NULL,
  "execution_mode" text NOT NULL,
  "authority_mode" text NOT NULL DEFAULT 'projection',
  "domain_ref_type" text NOT NULL,
  "domain_ref_id" text NOT NULL,
  "source_state" text,
  "state" text NOT NULL,
  "priority" text NOT NULL DEFAULT 'P2',
  "account_id" text,
  "source_run_id" text,
  "owner_id" text,
  "store_id" text,
  "warehouse_id" text,
  "sku_id" text,
  "idempotency_key" text NOT NULL,
  "attempt_count" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 3,
  "available_at" timestamptz,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "input_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "result_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_error_code" text,
  "last_error_message" text,
  "state_version" integer NOT NULL DEFAULT 1,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("domain", "idempotency_key"),
  UNIQUE ("domain", "domain_ref_type", "domain_ref_id"),
  CHECK (domain IN (
      'growth',
      'mabang_data',
      'mabang_images',
      'listing',
      'product',
      'files'
    )),
  CHECK (execution_mode IN ('human', 'system')),
  CHECK (authority_mode IN ('projection', 'foundation')),
  CHECK (state IN (
      'PENDING',
      'READY',
      'RUNNING',
      'PAUSE_REQUESTED',
      'PAUSED',
      'BLOCKED',
      'RETRY_WAIT',
      'SUCCEEDED',
      'PARTIAL_SUCCESS',
      'FAILED',
      'CANCELLED',
      'DISMISSED'
    )),
  CHECK (priority IN ('P0', 'P1', 'P2', 'P3')),
  CHECK (attempt_count >= 0),
  CHECK (max_attempts >= 1),
  CHECK (state_version >= 1)
);

CREATE TABLE "app"."foundation_warehouses" (
  "id" text,
  "canonical_key" text NOT NULL,
  "display_name" text NOT NULL,
  "normalized_name" text NOT NULL,
  "country_code" text,
  "country_name" text,
  "identity_status" text NOT NULL DEFAULT 'review_required',
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("canonical_key"),
  CHECK (identity_status IN ('confirmed', 'review_required', 'excluded')),
  CHECK ((identity_status = 'confirmed' AND country_code IS NOT NULL AND country_code <> '')
    OR identity_status <> 'confirmed')
);

CREATE TABLE "app"."growth_analysis_runs" (
  "id" text,
  "analysis_date" date NOT NULL,
  "inventory_batch_id" text NOT NULL,
  "order_watermark_at" timestamptz NOT NULL,
  "rule_set_id" text NOT NULL,
  "country_mapping_set_id" text NOT NULL,
  "shop_scope_fingerprint" text NOT NULL,
  "input_fingerprint" text NOT NULL,
  "status" text NOT NULL,
  "quality_status" text NOT NULL,
  "quality_summary_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "global_sku_count" integer NOT NULL DEFAULT 0,
  "country_sku_count" integer NOT NULL DEFAULT 0,
  "shop_count" integer NOT NULL DEFAULT 0,
  "shop_sku_count" integer NOT NULL DEFAULT 0,
  "signal_count" integer NOT NULL DEFAULT 0,
  "started_at" timestamptz,
  "validated_at" timestamptz,
  "published_at" timestamptz,
  "finished_at" timestamptz,
  "error_code" text,
  "error_summary" text,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("input_fingerprint"),
  CHECK (status IN ('pending', 'running', 'validating', 'published', 'failed', 'cancelled')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked')),
  CHECK (global_sku_count >= 0),
  CHECK (country_sku_count >= 0),
  CHECK (shop_count >= 0),
  CHECK (shop_sku_count >= 0),
  CHECK (signal_count >= 0)
);

CREATE TABLE "app"."growth_country_mapping_sets" (
  "id" text,
  "version" text NOT NULL,
  "status" text NOT NULL,
  "description" text NOT NULL,
  "content_sha256" text NOT NULL,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "activated_by" text,
  "activated_at" timestamptz,
  "retired_by" text,
  "retired_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("content_sha256"),
  UNIQUE ("version"),
  CHECK (status IN ('draft', 'active', 'retired'))
);

CREATE TABLE "app"."growth_data_quality_issues" (
  "id" text,
  "issue_key" text NOT NULL,
  "batch_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text,
  "issue_code" text NOT NULL,
  "severity" text NOT NULL,
  "message" text NOT NULL,
  "source_context_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" text NOT NULL DEFAULT 'open',
  "created_at" timestamptz NOT NULL,
  "resolved_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("issue_key"),
  CHECK (entity_type IN ('batch', 'order_raw_row', 'order_header', 'order_line', 'inventory_raw_row', 'inventory_snapshot', 'mapping')),
  CHECK (severity IN ('blocker', 'warning', 'information')),
  CHECK (status IN ('open', 'resolved', 'ignored'))
);

CREATE TABLE "app"."growth_focus_item_events" (
  "id" text,
  "focus_item_id" text NOT NULL,
  "event_type" text NOT NULL,
  "task_revision" integer NOT NULL,
  "from_status" text,
  "to_status" text NOT NULL,
  "actor_user_id" text NOT NULL,
  "actor_type" text NOT NULL,
  "reason_code" text,
  "note" text,
  "signal_id" text,
  "analysis_run_id" text,
  "evidence_snapshot_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "idempotency_key" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("focus_item_id", "task_revision"),
  UNIQUE ("focus_item_id", "idempotency_key"),
  CHECK (event_type IN (
      'CREATED',
      'ASSIGNED',
      'ACKNOWLEDGED',
      'STARTED',
      'MONITORING_STARTED',
      'BLOCKED',
      'RESOLVED',
      'DISMISSED',
      'REOPENED',
      'SIGNAL_REFRESHED',
      'NOT_HIT_IN_LATEST_RUN',
      'SCHEDULED'
    )),
  CHECK (task_revision >= 1),
  CHECK (from_status IS NULL
    OR from_status IN (
      'NEW',
      'ACKNOWLEDGED',
      'IN_PROGRESS',
      'MONITORING',
      'RESOLVED',
      'BLOCKED',
      'DISMISSED',
      'REOPENED'
    )),
  CHECK (to_status IN (
      'NEW',
      'ACKNOWLEDGED',
      'IN_PROGRESS',
      'MONITORING',
      'RESOLVED',
      'BLOCKED',
      'DISMISSED',
      'REOPENED'
    )),
  CHECK (actor_type IN ('user', 'system')),
  CHECK (idempotency_key <> '')
);

CREATE TABLE "app"."growth_focus_items" (
  "id" text,
  "task_key" text NOT NULL,
  "task_type" text NOT NULL,
  "current_signal_id" text,
  "first_analysis_run_id" text NOT NULL,
  "last_analysis_run_id" text NOT NULL,
  "owner_user_id" text,
  "internal_shop_id" text,
  "country_code" text,
  "source_warehouse_name" text,
  "normalized_warehouse_name" text,
  "platform" text,
  "category_l1" text,
  "category_l2" text,
  "subject_type" text NOT NULL,
  "normalized_source_sku" text,
  "priority" text NOT NULL,
  "status" text NOT NULL DEFAULT 'NEW',
  "reason_code" text NOT NULL,
  "recommended_action_code" text NOT NULL,
  "evidence_snapshot_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "consecutive_hit_count" integer NOT NULL DEFAULT 1,
  "is_hit_in_latest_run" integer NOT NULL DEFAULT 1,
  "first_detected_at" timestamptz NOT NULL,
  "last_detected_at" timestamptz NOT NULL,
  "acknowledged_at" timestamptz,
  "started_at" timestamptz,
  "due_at" timestamptz,
  "snoozed_until" text,
  "blocked_reason_code" text,
  "resolution_code" text,
  "resolution_note" text,
  "resolved_at" timestamptz,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (task_type IN (
      'DATA_BLOCKED',
      'STORE_WATCH',
      'INVENTORY_RISK',
      'GROWTH_OPPORTUNITY',
      'BLUE_OCEAN',
      'CROSS_COUNTRY_CANDIDATE',
      'STORE_SALES_DECLINE',
      'STORE_ASSORTMENT_GAP',
      'SKU_SALES_GROWTH',
      'SKU_SALES_DECLINE',
      'NEW_PRODUCT_OPPORTUNITY'
    )),
  CHECK (subject_type IN (
      'shop',
      'shop_category',
      'shop_sku',
      'warehouse_sku',
      'country_category',
      'sku',
      'data_configuration'
    )),
  CHECK (priority IN ('P0', 'P1', 'P2', 'P3')),
  CHECK (status IN (
      'NEW',
      'ACKNOWLEDGED',
      'IN_PROGRESS',
      'MONITORING',
      'RESOLVED',
      'BLOCKED',
      'DISMISSED',
      'REOPENED'
    )),
  CHECK (consecutive_hit_count >= 1),
  CHECK (is_hit_in_latest_run IN (0, 1)),
  CHECK (revision >= 1),
  CHECK (task_key <> ''),
  CHECK (reason_code <> ''),
  CHECK (recommended_action_code <> ''),
  CHECK ((source_warehouse_name IS NULL AND normalized_warehouse_name IS NULL)
    OR (
      source_warehouse_name IS NOT NULL
      AND source_warehouse_name <> ''
      AND normalized_warehouse_name IS NOT NULL
      AND normalized_warehouse_name <> ''
    )),
  CHECK (subject_type <> 'warehouse_sku'
    OR normalized_warehouse_name IS NOT NULL),
  CHECK (status <> 'BLOCKED' OR (blocked_reason_code IS NOT NULL AND blocked_reason_code <> '')),
  CHECK (status <> 'MONITORING'
    OR due_at IS NOT NULL
    OR snoozed_until IS NOT NULL),
  CHECK (status NOT IN ('RESOLVED', 'DISMISSED')
    OR (
      resolution_code IS NOT NULL
      AND resolution_code <> ''
      AND resolved_at IS NOT NULL
    ))
);

CREATE TABLE "app"."growth_inventory_raw_rows" (
  "id" text,
  "batch_id" text NOT NULL,
  "sheet_name" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "raw_values_json" jsonb NOT NULL,
  "raw_types_json" jsonb NOT NULL,
  "redacted_fields_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "row_hash" text NOT NULL,
  "parse_status" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "source_row_number"),
  CHECK (source_row_number >= 2),
  CHECK (parse_status IN ('parsed', 'review_required', 'rejected'))
);

CREATE TABLE "app"."growth_inventory_snapshots" (
  "id" text,
  "batch_id" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "source_sku" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "mapped_product_id" text,
  "warehouse_name" text,
  "available_quantity" numeric,
  "physical_quantity" numeric,
  "locked_quantity" numeric,
  "in_transit_quantity" numeric,
  "pending_shipment_quantity" numeric,
  "sellable_quantity" numeric,
  "sellable_quantity_status" text NOT NULL DEFAULT 'unconfirmed',
  "source_predicted_daily_sales" numeric,
  "predicted_daily_sales_semantic_status" text NOT NULL DEFAULT 'unconfirmed',
  "days_of_supply" numeric,
  "days_of_supply_status" text NOT NULL DEFAULT 'unavailable',
  "snapshot_at" timestamptz,
  "mapping_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "normalized_warehouse_name" text NOT NULL DEFAULT '',
  "product_status" text,
  "category_level_1" text,
  "category_level_2" text,
  "category_level_3" text,
  "source_visible_sales_7d" numeric,
  "source_visible_sales_28d" numeric,
  "source_visible_sales_42d" numeric,
  "source_scope_status" text NOT NULL DEFAULT 'unconfirmed',
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "source_row_number"),
  CHECK (source_row_number >= 2),
  CHECK (sellable_quantity_status IN ('confirmed', 'unconfirmed', 'unavailable')),
  CHECK (predicted_daily_sales_semantic_status IN ('confirmed', 'unconfirmed', 'unavailable')),
  CHECK (days_of_supply_status IN ('confirmed', 'unconfirmed', 'unavailable')),
  CHECK (mapping_status IN ('matched', 'country_unresolved', 'ambiguous', 'unmatched')),
  CHECK (quality_status IN ('confirmed', 'review_required', 'unconfirmed')),
  CHECK (source_scope_status IN ('unconfirmed', 'confirmed'))
);

CREATE TABLE "app"."growth_mapping_events" (
  "id" text,
  "mapping_type" text NOT NULL,
  "mapping_id" text NOT NULL,
  "action" text NOT NULL,
  "before_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "after_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "actor_label" text NOT NULL,
  "request_id" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (mapping_type IN ('shop', 'product')),
  CHECK (action IN ('confirmed', 'revoked'))
);

CREATE TABLE "app"."growth_mapping_issues" (
  "id" text,
  "issue_key" text NOT NULL,
  "issue_type" text NOT NULL,
  "source_batch_id" text NOT NULL,
  "source_row_id" text,
  "source_value" text NOT NULL,
  "candidate_values_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "reason" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "resolved_value" text,
  "resolved_by" text,
  "resolved_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("issue_key"),
  CHECK (issue_type IN (
    'shop_unmatched', 'shop_ambiguous', 'country_unresolved', 'sku_unmatched',
    'sku_ambiguous', 'product_country_conflict', 'duplicate_order_key', 'duplicate_line_key'
  )),
  CHECK (status IN ('open', 'resolved', 'revoked', 'ignored'))
);

CREATE TABLE "app"."growth_order_headers" (
  "id" text,
  "business_key" text NOT NULL,
  "business_key_version" text NOT NULL,
  "platform" text NOT NULL,
  "source_shop_name" text NOT NULL,
  "normalized_source_shop_name" text NOT NULL,
  "internal_shop_id" text,
  "mapped_country" text,
  "source_order_id" text NOT NULL,
  "order_status" text NOT NULL,
  "paid_at" timestamptz,
  "cancelled_at" timestamptz,
  "order_currency" text,
  "order_amount" numeric,
  "order_amount_source_field" text,
  "effective_status" text NOT NULL,
  "first_source_batch_id" text NOT NULL,
  "source_batch_id" text NOT NULL,
  "source_quality_status" text NOT NULL,
  "first_seen_at" timestamptz NOT NULL,
  "last_seen_at" timestamptz NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("business_key_version", "business_key"),
  CHECK (effective_status IN ('valid', 'pending', 'invalid_cancelled', 'unconfirmed')),
  CHECK (source_quality_status IN ('confirmed', 'review_required', 'invalid')),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."growth_order_inventory_links" (
  "id" text,
  "order_line_id" text NOT NULL,
  "order_source_batch_id" text NOT NULL,
  "inventory_snapshot_id" text,
  "inventory_source_batch_id" text NOT NULL,
  "match_key_version" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "normalized_source_warehouse_name" text NOT NULL,
  "match_status" text NOT NULL,
  "unmatched_reason" text,
  "order_effective_status" text NOT NULL,
  "is_current" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("order_line_id", "inventory_source_batch_id"),
  CHECK (match_key_version = 'source_sku_warehouse_v1'),
  CHECK (match_status IN ('matched', 'unmatched')),
  CHECK (order_effective_status IN ('valid', 'pending', 'invalid_cancelled', 'unconfirmed')),
  CHECK (is_current IN (0, 1))
);

CREATE TABLE "app"."growth_order_lines" (
  "id" text,
  "order_header_id" text NOT NULL,
  "first_source_batch_id" text NOT NULL,
  "source_batch_id" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "source_line_key" text NOT NULL,
  "source_line_key_version" text NOT NULL,
  "line_occurrence" integer NOT NULL,
  "dedupe_confidence" text NOT NULL,
  "source_sku" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "platform_sku" text,
  "mapped_product_id" text,
  "mapped_country" text,
  "quantity" numeric NOT NULL,
  "line_amount" numeric,
  "line_amount_status" text NOT NULL,
  "product_name" text,
  "mapping_status" text NOT NULL,
  "effective_status" text NOT NULL,
  "is_current" integer NOT NULL DEFAULT 1,
  "first_seen_at" timestamptz NOT NULL,
  "last_seen_at" timestamptz NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "source_warehouse_name" text,
  "normalized_source_warehouse_name" text,
  PRIMARY KEY ("id"),
  UNIQUE ("source_line_key_version", "source_line_key"),
  CHECK (source_row_number >= 2),
  CHECK (line_occurrence >= 1),
  CHECK (dedupe_confidence IN ('technical_occurrence', 'source_identifier')),
  CHECK (line_amount_status IN ('confirmed', 'unconfirmed', 'unavailable')),
  CHECK (mapping_status IN ('matched', 'manually_confirmed', 'country_unresolved', 'ambiguous', 'unmatched', 'revoked')),
  CHECK (effective_status IN ('valid', 'pending', 'invalid_cancelled', 'unconfirmed')),
  CHECK (is_current IN (0, 1)),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."growth_order_raw_rows" (
  "id" text,
  "batch_id" text NOT NULL,
  "sheet_name" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "raw_values_json" jsonb NOT NULL,
  "raw_types_json" jsonb NOT NULL,
  "redacted_fields_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "row_hash" text NOT NULL,
  "parse_status" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "source_row_number"),
  CHECK (source_row_number >= 2),
  CHECK (parse_status IN ('parsed', 'review_required', 'rejected'))
);

CREATE TABLE "app"."growth_rule_sets" (
  "id" text,
  "version" text NOT NULL,
  "status" text NOT NULL,
  "metrics_contract_version" text NOT NULL,
  "parameters_json" jsonb NOT NULL,
  "content_sha256" text NOT NULL,
  "effective_from" text NOT NULL,
  "effective_to" text,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "activated_by" text,
  "activated_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("content_sha256"),
  UNIQUE ("version"),
  CHECK (status IN ('draft', 'active', 'retired')),
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE "app"."growth_shop_daily_metrics" (
  "id" text,
  "analysis_run_id" text NOT NULL,
  "analysis_date" date NOT NULL,
  "internal_shop_id" text NOT NULL,
  "display_name" text NOT NULL,
  "platform" text NOT NULL,
  "owner_user_id" text,
  "country_code" text NOT NULL,
  "own_sales_quantity_7d" numeric NOT NULL DEFAULT 0,
  "own_sales_quantity_28d" numeric NOT NULL DEFAULT 0,
  "valid_order_count_7d" integer NOT NULL DEFAULT 0,
  "valid_order_count_28d" integer NOT NULL DEFAULT 0,
  "eligible_saleable_sku_count" integer,
  "sold_eligible_sku_count_28d" integer,
  "saleable_coverage_rate_28d" numeric,
  "eligible_high_performance_sku_count" integer,
  "sold_high_performance_sku_count_28d" integer,
  "high_performance_coverage_rate_28d" numeric,
  "key_performer_count" integer NOT NULL DEFAULT 0,
  "growth_focus_count" integer NOT NULL DEFAULT 0,
  "new_opportunity_count" integer NOT NULL DEFAULT 0,
  "slow_risk_count" integer NOT NULL DEFAULT 0,
  "low_stock_risk_count" integer NOT NULL DEFAULT 0,
  "availability_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "reason_code" text NOT NULL,
  "metrics_version" text NOT NULL,
  "country_mapping_set_id" text NOT NULL,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "calculated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("analysis_run_id", "internal_shop_id"),
  CHECK (valid_order_count_7d >= 0),
  CHECK (valid_order_count_28d >= 0),
  CHECK (key_performer_count >= 0),
  CHECK (growth_focus_count >= 0),
  CHECK (new_opportunity_count >= 0),
  CHECK (slow_risk_count >= 0),
  CHECK (low_stock_risk_count >= 0),
  CHECK (availability_status IN ('available', 'degraded', 'unavailable')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked'))
);

CREATE TABLE "app"."growth_shop_sku_coverage_snapshots" (
  "id" text,
  "internal_shop_id" text NOT NULL,
  "product_sku_id" text NOT NULL,
  "coverage_semantic" text NOT NULL,
  "source_system" text NOT NULL,
  "source_evidence_id" text NOT NULL,
  "observed_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("internal_shop_id", "product_sku_id", "source_system", "observed_at"),
  CHECK (coverage_semantic = 'current_online')
);

CREATE TABLE "app"."growth_shop_sku_daily_metrics" (
  "id" text,
  "analysis_run_id" text NOT NULL,
  "analysis_date" date NOT NULL,
  "internal_shop_id" text NOT NULL,
  "country_code" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "source_sku" text NOT NULL,
  "product_name" text,
  "category_l1" text,
  "category_l2" text,
  "mapped_product_id" text,
  "own_sales_quantity_7d" numeric NOT NULL DEFAULT 0,
  "own_sales_quantity_28d" numeric NOT NULL DEFAULT 0,
  "valid_order_count_7d" integer NOT NULL DEFAULT 0,
  "valid_order_count_28d" integer NOT NULL DEFAULT 0,
  "last_sold_at" timestamptz,
  "source_visible_sales_7d" numeric,
  "source_visible_sales_28d" numeric,
  "source_visible_sales_42d" numeric,
  "shop_to_source_visible_ratio_28d" numeric,
  "shop_to_source_visible_ratio_percentile_28d" numeric,
  "shop_sales_percentile_28d" numeric,
  "eligible_saleable" integer NOT NULL DEFAULT 0,
  "eligible_high_performance" integer NOT NULL DEFAULT 0,
  "is_key_performer" integer NOT NULL DEFAULT 0,
  "is_growth_focus_candidate" integer NOT NULL DEFAULT 0,
  "available_quantity" numeric,
  "availability_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "reason_code" text NOT NULL,
  "metrics_version" text NOT NULL,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "calculated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("analysis_run_id", "internal_shop_id", "normalized_source_sku"),
  CHECK (valid_order_count_7d >= 0),
  CHECK (valid_order_count_28d >= 0),
  CHECK (eligible_saleable IN (0, 1)),
  CHECK (eligible_high_performance IN (0, 1)),
  CHECK (is_key_performer IN (0, 1)),
  CHECK (is_growth_focus_candidate IN (0, 1)),
  CHECK (availability_status IN ('available', 'degraded', 'unavailable')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked'))
);

CREATE TABLE "app"."growth_shop_sku_observations" (
  "id" text,
  "observation_key" text NOT NULL,
  "coverage_semantic" text NOT NULL DEFAULT 'historical_observed',
  "platform" text NOT NULL,
  "source_shop_name" text NOT NULL,
  "normalized_source_shop_name" text NOT NULL,
  "internal_shop_id" text,
  "source_sku" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "mapped_product_id" text,
  "first_observed_at" timestamptz,
  "last_observed_at" timestamptz,
  "observed_order_count" integer NOT NULL DEFAULT 0,
  "observed_line_count" integer NOT NULL DEFAULT 0,
  "observed_quantity" numeric NOT NULL DEFAULT 0,
  "first_source_batch_id" text NOT NULL,
  "last_source_batch_id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("observation_key"),
  CHECK (coverage_semantic = 'historical_observed'),
  CHECK (observed_order_count >= 0),
  CHECK (observed_line_count >= 0)
);

CREATE TABLE "app"."growth_shop_source_mappings" (
  "id" text,
  "source_system" text NOT NULL,
  "source_shop_name" text NOT NULL,
  "normalized_source_shop_name" text NOT NULL,
  "internal_shop_id" text,
  "platform" text NOT NULL,
  "country_code" text,
  "mapping_status" text NOT NULL,
  "mapping_source" text NOT NULL,
  "first_source_batch_id" text,
  "last_source_batch_id" text,
  "confirmed_by" text,
  "confirmed_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "platform", "normalized_source_shop_name"),
  CHECK (mapping_status IN ('matched', 'manually_confirmed', 'ambiguous', 'unmatched', 'revoked')),
  CHECK (mapping_source IN ('exact', 'manual', 'unresolved', 'revoked'))
);

CREATE TABLE "app"."growth_shops" (
  "id" text,
  "internal_shop_code" text NOT NULL,
  "display_name" text NOT NULL,
  "platform" text NOT NULL,
  "country_code" text NOT NULL,
  "country_name" text NOT NULL,
  "owner_user_id" text,
  "primary_category_scope_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "status" text NOT NULL DEFAULT 'active',
  "identity_status" text NOT NULL DEFAULT 'confirmed',
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("internal_shop_code"),
  CHECK (status IN ('active', 'inactive')),
  CHECK (identity_status IN ('confirmed', 'review_required')),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."growth_signals" (
  "id" text,
  "analysis_run_id" text NOT NULL,
  "dedupe_key" text NOT NULL,
  "signal_type" text NOT NULL,
  "rule_code" text NOT NULL,
  "rule_version" text NOT NULL,
  "subject_type" text NOT NULL,
  "country_code" text,
  "source_warehouse_name" text,
  "normalized_warehouse_name" text,
  "normalized_source_sku" text,
  "internal_shop_id" text,
  "severity" text NOT NULL,
  "reason_code" text NOT NULL,
  "recommended_action_code" text NOT NULL,
  "availability_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "detected_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("analysis_run_id", "dedupe_key"),
  CHECK (signal_type IN ('opportunity', 'risk', 'highlight', 'data_quality')),
  CHECK (subject_type IN ('sku', 'warehouse_sku', 'shop_sku', 'shop', 'run')),
  CHECK (severity IN ('information', 'warning', 'high', 'critical')),
  CHECK (availability_status IN ('available', 'degraded', 'unavailable')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked')),
  CHECK ((source_warehouse_name IS NULL AND normalized_warehouse_name IS NULL)
    OR (
      source_warehouse_name IS NOT NULL
      AND source_warehouse_name <> ''
      AND normalized_warehouse_name IS NOT NULL
      AND normalized_warehouse_name <> ''
    )),
  CHECK (subject_type <> 'warehouse_sku'
    OR normalized_warehouse_name IS NOT NULL)
);

CREATE TABLE "app"."growth_sku_daily_metrics" (
  "id" text,
  "analysis_run_id" text NOT NULL,
  "analysis_date" date NOT NULL,
  "scope_type" text NOT NULL,
  "scope_key" text NOT NULL,
  "country_code" text,
  "normalized_source_sku" text NOT NULL,
  "source_sku" text NOT NULL,
  "product_name" text,
  "product_status" text NOT NULL,
  "category_l1" text,
  "category_l2" text,
  "mapped_product_id" text,
  "mapping_status" text NOT NULL,
  "warehouse_count" integer NOT NULL,
  "available_quantity" numeric,
  "in_transit_quantity" numeric,
  "source_predicted_daily_sales_country_sku" numeric,
  "source_visible_sales_7d" numeric,
  "source_visible_sales_28d" numeric,
  "source_visible_sales_42d" numeric,
  "effective_daily_sales_28d" numeric,
  "computed_days_of_supply" numeric,
  "days_of_supply_status" text NOT NULL,
  "demand_percentile_28d" numeric,
  "assortment_percentile" numeric,
  "inventory_percentile" numeric,
  "comparison_scope" text,
  "comparison_sample_size" bigint,
  "assortment_status" text,
  "warehouse_supply_summary_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "supply_risk_warehouse_count" integer NOT NULL DEFAULT 0,
  "supply_critical_warehouse_count" integer NOT NULL DEFAULT 0,
  "supply_warning_warehouse_count" integer NOT NULL DEFAULT 0,
  "supply_data_issue_warehouse_count" integer NOT NULL DEFAULT 0,
  "is_source_high_performance" integer NOT NULL DEFAULT 0,
  "is_new" integer NOT NULL DEFAULT 0,
  "new_age_days" integer,
  "availability_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "reason_code" text NOT NULL,
  "metrics_version" text NOT NULL,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "calculated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("analysis_run_id", "scope_type", "scope_key", "normalized_source_sku"),
  CHECK (scope_type IN ('global', 'country')),
  CHECK (warehouse_count >= 1),
  CHECK (assortment_status IS NULL
    OR assortment_status IN (
      'ASSORTMENT_VERIFIED_HIGH',
      'ASSORTMENT_VERIFIED_MID',
      'ASSORTMENT_LOW',
      'ASSORTMENT_DATA_INSUFFICIENT'
    )),
  CHECK (supply_risk_warehouse_count >= 0),
  CHECK (supply_critical_warehouse_count >= 0),
  CHECK (supply_warning_warehouse_count >= 0),
  CHECK (supply_data_issue_warehouse_count >= 0),
  CHECK (is_source_high_performance IN (0, 1)),
  CHECK (is_new IN (0, 1)),
  CHECK (availability_status IN ('available', 'degraded', 'unavailable')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked')),
  CHECK ((scope_type = 'global' AND scope_key = 'GLOBAL' AND country_code IS NULL)
    OR (scope_type = 'country' AND scope_key = country_code AND country_code IS NOT NULL)),
  CHECK (metrics_version <> 'GRV2-METRICS-1.2.0'
    OR (
      computed_days_of_supply IS NULL
      AND days_of_supply_status = 'warehouse_aggregate_only'
      AND assortment_status IS NOT NULL
    ))
);

CREATE TABLE "app"."growth_sku_warehouse_daily_metrics" (
  "id" text,
  "analysis_run_id" text NOT NULL,
  "analysis_date" date NOT NULL,
  "country_code" text NOT NULL,
  "source_warehouse_name" text NOT NULL,
  "normalized_warehouse_name" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "source_sku" text NOT NULL,
  "product_name" text,
  "product_status" text NOT NULL,
  "category_l1" text,
  "category_l2" text,
  "mapped_product_id" text,
  "mapping_status" text NOT NULL,
  "available_quantity" numeric,
  "in_transit_quantity" numeric,
  "source_current_sellable_days" numeric,
  "source_predicted_daily_sales" numeric,
  "source_visible_sales_7d" numeric,
  "source_visible_sales_28d" numeric,
  "source_visible_sales_42d" numeric,
  "supply_status" text NOT NULL,
  "slow_moving_status" text NOT NULL,
  "availability_status" text NOT NULL,
  "quality_status" text NOT NULL,
  "reason_code" text NOT NULL,
  "metrics_version" text NOT NULL,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "calculated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("analysis_run_id", "country_code", "normalized_warehouse_name", "normalized_source_sku"),
  CHECK (source_current_sellable_days IS NULL OR source_current_sellable_days >= 0),
  CHECK (supply_status IN (
      'SUPPLY_DATA_INSUFFICIENT',
      'SUPPLY_DATA_CONFLICT',
      'OUT_OF_STOCK',
      'IN_TRANSIT_ONLY',
      'SUPPLY_CRITICAL',
      'SUPPLY_WARNING',
      'SUPPLY_HEALTHY'
    )),
  CHECK (slow_moving_status IN (
      'NOT_APPLICABLE',
      'NORMAL',
      'SLOW_MOVING_WATCH',
      'SLOW_MOVING_RISK',
      'SLOW_MOVING_SEVERE'
    )),
  CHECK (availability_status IN ('available', 'degraded', 'unavailable')),
  CHECK (quality_status IN ('confirmed', 'degraded', 'blocked')),
  CHECK (normalized_warehouse_name <> ''),
  CHECK (country_code <> '' AND country_code <> 'ZZ')
);

CREATE TABLE "app"."growth_sku_warehouse_sales_metrics" (
  "id" text,
  "inventory_snapshot_id" text NOT NULL,
  "inventory_source_batch_id" text NOT NULL,
  "order_source_batch_id" text,
  "snapshot_at" timestamptz NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "normalized_source_warehouse_name" text NOT NULL,
  "own_sales_quantity_7d" numeric,
  "own_sales_order_count_7d" integer,
  "own_sales_effective_line_count_7d" integer,
  "own_sales_window_started_at" timestamptz,
  "own_sales_window_ended_at" timestamptz,
  "own_sales_quantity_7d_status" text NOT NULL,
  "source_visible_sales_7d" numeric,
  "source_visible_sales_28d" numeric,
  "source_visible_sales_42d" numeric,
  "source_predicted_daily_sales" numeric,
  "source_predicted_daily_sales_status" text NOT NULL,
  "source_scope_status" text NOT NULL DEFAULT 'unconfirmed',
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("inventory_snapshot_id"),
  CHECK (own_sales_quantity_7d_status IN ('confirmed', 'unavailable')),
  CHECK (source_predicted_daily_sales_status IN ('source_prediction_not_actual', 'unavailable')),
  CHECK (source_scope_status IN ('unconfirmed', 'confirmed'))
);

CREATE TABLE "app"."growth_source_batches" (
  "id" text,
  "source_type" text NOT NULL,
  "source_module" text NOT NULL,
  "source_file_id" text,
  "source_filename" text,
  "source_sha256" text NOT NULL,
  "source_account_id" text,
  "idempotency_key" text NOT NULL,
  "query_started_at" timestamptz,
  "query_ended_at" timestamptz,
  "collected_at" timestamptz,
  "imported_at" timestamptz,
  "source_scope_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "source_headers_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "redacted_headers_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "row_count" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL,
  "error_code" text,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "source_scope_status" text NOT NULL DEFAULT 'unconfirmed',
  "pii_filtered_field_count" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  UNIQUE ("source_type", "idempotency_key"),
  CHECK (source_type IN ('mabang_order', 'mabang_inventory', 'shop_listing_import')),
  CHECK (row_count >= 0),
  CHECK (status IN ('applying', 'applied', 'failed')),
  CHECK (source_scope_status IN ('unconfirmed', 'confirmed')),
  CHECK (pii_filtered_field_count >= 0)
);

CREATE TABLE "app"."growth_warehouse_country_mappings" (
  "id" text,
  "mapping_set_id" text NOT NULL,
  "source_system" text NOT NULL,
  "source_warehouse_name" text NOT NULL,
  "normalized_warehouse_name" text NOT NULL,
  "country_code" text NOT NULL,
  "country_name" text NOT NULL,
  "mapping_status" text NOT NULL,
  "exclusion_reason" text,
  "evidence_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "confirmed_by" text NOT NULL,
  "confirmed_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("mapping_set_id", "source_system", "normalized_warehouse_name"),
  CHECK (source_system = 'mabang_inventory'),
  CHECK (country_code <> '' AND country_code <> 'ZZ'),
  CHECK (mapping_status IN ('confirmed', 'excluded')),
  CHECK ((mapping_status = 'confirmed' AND exclusion_reason IS NULL)
    OR (mapping_status = 'excluded' AND exclusion_reason IS NOT NULL AND exclusion_reason <> ''))
);

CREATE TABLE "app"."mabang_account_profiles" (
  "id" text,
  "name" text NOT NULL,
  "username" text NOT NULL,
  "encrypted_password" text NOT NULL,
  "enabled" integer NOT NULL DEFAULT 1,
  "last_verified_at" timestamptz,
  "last_verify_status" text,
  "last_verify_message" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "app"."mabang_filter_option_cache" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "account_profile_id" text NOT NULL,
  "manager" text NOT NULL DEFAULT '',
  "shop_name" text NOT NULL DEFAULT '',
  "platform" text NOT NULL DEFAULT '',
  "region" text NOT NULL DEFAULT '',
  "warehouse" text NOT NULL DEFAULT '',
  "order_status" text NOT NULL DEFAULT '',
  "sku" text NOT NULL DEFAULT '',
  "logistics_channel" text NOT NULL DEFAULT '',
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("account_profile_id", "manager", "shop_name", "platform", "region", "warehouse", "order_status", "sku", "logistics_channel")
);

CREATE TABLE "app"."mabang_sku_image_batches" (
  "id" text,
  "account_id" text NOT NULL,
  "source_batch_id" text,
  "mode" text NOT NULL,
  "status" text NOT NULL,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  "paused_at" timestamptz,
  "current_page" integer NOT NULL DEFAULT 0,
  "total_pages" integer,
  "discovered_skus" integer NOT NULL DEFAULT 0,
  "downloaded_images" integer NOT NULL DEFAULT 0,
  "missing_images" integer NOT NULL DEFAULT 0,
  "duplicate_images" integer NOT NULL DEFAULT 0,
  "failed_images" integer NOT NULL DEFAULT 0,
  "linked_products" integer NOT NULL DEFAULT 0,
  "shared_country_links" integer NOT NULL DEFAULT 0,
  "filename_mismatches" integer NOT NULL DEFAULT 0,
  "interface_profile_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_error_code" text,
  "last_error_message" text,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "sync_run_id" text,
  "segment_no" integer,
  "start_page" integer,
  "end_page" integer,
  PRIMARY KEY ("id"),
  CHECK (mode IN ('full_initial', 'missing_only', 'retry_failed')),
  CHECK (status IN (
    'pending', 'running', 'pause_requested', 'paused',
    'completed', 'partial_success', 'failed'
  )),
  CHECK (current_page >= 0),
  CHECK (total_pages IS NULL OR total_pages >= 0),
  CHECK (discovered_skus >= 0),
  CHECK (downloaded_images >= 0),
  CHECK (missing_images >= 0),
  CHECK (duplicate_images >= 0),
  CHECK (failed_images >= 0),
  CHECK (linked_products >= 0),
  CHECK (shared_country_links >= 0),
  CHECK (filename_mismatches >= 0),
  CHECK (segment_no IS NULL OR segment_no >= 1),
  CHECK (start_page IS NULL OR start_page >= 1),
  CHECK (end_page IS NULL OR end_page >= 0)
);

CREATE TABLE "app"."mabang_sku_image_checkpoints" (
  "id" text,
  "batch_id" text NOT NULL,
  "page_number" integer NOT NULL,
  "page_hash" text NOT NULL,
  "row_count" integer NOT NULL DEFAULT 0,
  "discovered_count" integer NOT NULL DEFAULT 0,
  "failed_count" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL,
  "error_code" text,
  "completed_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "page_number"),
  CHECK (page_number >= 1),
  CHECK (row_count >= 0),
  CHECK (discovered_count >= 0),
  CHECK (failed_count >= 0),
  CHECK (status IN ('running', 'completed', 'failed', 'repeated'))
);

CREATE TABLE "app"."mabang_sku_image_discoveries" (
  "id" text,
  "batch_id" text NOT NULL,
  "source_sku" text NOT NULL,
  "source_sku_normalized" text NOT NULL,
  "product_name" text,
  "warehouse_name" text,
  "source_image_url" text,
  "image_src" text,
  "image_data_src" text,
  "image_srcset" text,
  "image_background_url" text,
  "source_kind" text NOT NULL,
  "source_page" integer NOT NULL,
  "source_row_number" integer NOT NULL,
  "filename_sku" text,
  "validation_status" text NOT NULL DEFAULT 'pending',
  "quality_issue_code" text,
  "download_status" text NOT NULL DEFAULT 'pending',
  "asset_id" text,
  "download_attempts" integer NOT NULL DEFAULT 0,
  "http_status" integer,
  "discovered_at" timestamptz NOT NULL,
  "last_checked_at" timestamptz NOT NULL,
  "error_code" text,
  "error_message" text,
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "source_page", "source_row_number", "source_sku_normalized"),
  CHECK (source_kind IN ('interface', 'dom', 'cos_network', 'retry')),
  CHECK (source_page >= 1),
  CHECK (source_row_number >= 1),
  CHECK (validation_status IN ('pending', 'valid', 'warning', 'invalid', 'missing')),
  CHECK (download_status IN ('pending', 'skipped', 'downloaded', 'duplicate', 'missing', 'failed')),
  CHECK (download_attempts >= 0)
);

CREATE TABLE "app"."mabang_sku_image_discovery_images" (
  "id" text,
  "discovery_id" text NOT NULL,
  "image_index" integer NOT NULL,
  "source_url" text NOT NULL,
  "source_url_hash" text NOT NULL,
  "source_kind" text NOT NULL,
  "download_status" text NOT NULL DEFAULT 'pending',
  "asset_id" text,
  "download_attempts" integer NOT NULL DEFAULT 0,
  "http_status" integer,
  "error_code" text,
  "error_message" text,
  "discovered_at" timestamptz NOT NULL,
  "last_checked_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("discovery_id", "source_url_hash"),
  CHECK (image_index >= 0),
  CHECK (source_kind IN (
    'src', 'data_src', 'srcset', 'background', 'interface', 'retry'
  )),
  CHECK (download_status IN ('pending', 'skipped', 'downloaded', 'duplicate', 'missing', 'failed')),
  CHECK (download_attempts >= 0)
);

CREATE TABLE "app"."mabang_sku_image_sync_runs" (
  "id" text,
  "account_id" text NOT NULL,
  "status" text NOT NULL,
  "next_page" integer NOT NULL DEFAULT 1,
  "total_pages" integer,
  "segment_count" integer NOT NULL DEFAULT 0,
  "discovered_skus" integer NOT NULL DEFAULT 0,
  "discovered_images" integer NOT NULL DEFAULT 0,
  "downloaded_images" integer NOT NULL DEFAULT 0,
  "duplicate_images" integer NOT NULL DEFAULT 0,
  "failed_images" integer NOT NULL DEFAULT 0,
  "matched_skus" integer NOT NULL DEFAULT 0,
  "unmatched_skus" integer NOT NULL DEFAULT 0,
  "last_batch_id" text,
  "last_error_code" text,
  "last_error_message" text,
  "created_by" text NOT NULL,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (status IN (
    'pending', 'running', 'completed', 'partial_success', 'failed'
  )),
  CHECK (next_page >= 1),
  CHECK (total_pages IS NULL OR total_pages >= 0),
  CHECK (segment_count >= 0),
  CHECK (discovered_skus >= 0),
  CHECK (discovered_images >= 0),
  CHECK (downloaded_images >= 0),
  CHECK (duplicate_images >= 0),
  CHECK (failed_images >= 0),
  CHECK (matched_skus >= 0),
  CHECK (unmatched_skus >= 0)
);

CREATE TABLE "app"."managed_files" (
  "id" text,
  "lifecycle_item_id" text NOT NULL,
  "scan_id" text NOT NULL,
  "root_key" text NOT NULL,
  "relative_path" text NOT NULL,
  "source_type" text NOT NULL,
  "job_id" text,
  "mime_type" text NOT NULL,
  "file_size" bigint NOT NULL,
  "file_hash" text NOT NULL,
  "file_created_at" timestamptz NOT NULL,
  "status" text NOT NULL DEFAULT 'available',
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "registered_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("root_key", "relative_path"),
  UNIQUE ("lifecycle_item_id"),
  CHECK (root_key IN ('ad_upload', 'ad_output', 'ad_temp', 'main_temp')),
  CHECK (source_type IN (
    'advertising_source',
    'advertising_output',
    'advertising_report'
  )),
  CHECK (file_size >= 0),
  CHECK (length(file_hash) = 64),
  CHECK (status IN ('available', 'quarantined', 'restored', 'deleted'))
);

CREATE TABLE "app"."operation_audit_events" (
  "id" text,
  "request_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "module" text NOT NULL,
  "action" text NOT NULL,
  "http_method" text,
  "request_path" text,
  "status" text NOT NULL,
  "http_status" integer,
  "duration_ms" integer,
  "source_ip" text,
  "actor_type" text,
  "actor_identifier" text,
  "task_id" text,
  "run_id" text,
  "file_id" text,
  "error_stage" text,
  "error_code" text,
  "error_summary" text,
  "metadata_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "app"."price_control_automation_settings" (
  "id" text,
  "enabled" integer NOT NULL DEFAULT 0,
  "interval_minutes" integer NOT NULL DEFAULT 60,
  "dingtalk_config_id" text,
  "notify_on_change" integer NOT NULL DEFAULT 1,
  "notify_on_failure" integer NOT NULL DEFAULT 1,
  "last_run_at" timestamptz,
  "last_run_status" text,
  "last_notification_at" timestamptz,
  "last_notification_status" text,
  "next_run_at" timestamptz,
  "last_error_code" text,
  "last_error_message" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (id = 'default'),
  CHECK (enabled IN (0,1)),
  CHECK (interval_minutes BETWEEN 15 AND 1440),
  CHECK (notify_on_change IN (0,1)),
  CHECK (notify_on_failure IN (0,1)),
  CHECK (last_run_status IS NULL OR last_run_status IN ('SUCCEEDED','FAILED','PARTIAL_SUCCESS')),
  CHECK (last_notification_status IS NULL OR last_notification_status IN ('SENT','SKIPPED','FAILED','NOT_CONFIGURED'))
);

CREATE TABLE "app"."price_control_price_snapshots" (
  "id" text,
  "sync_run_id" text NOT NULL,
  "apply_no" text NOT NULL,
  "source_row_key" text NOT NULL,
  "price_key" text NOT NULL,
  "country_code" text NOT NULL,
  "category_name" text,
  "sku" text NOT NULL,
  "product_name_cn" text,
  "sku_status" text,
  "platform" text NOT NULL,
  "shop_type" text NOT NULL,
  "price_type" text NOT NULL,
  "price_value" text NOT NULL,
  "effective_at" timestamptz NOT NULL,
  "row_fingerprint" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("apply_no", "price_key"),
  CHECK (platform IN ('LAZADA','SHOPEE','TIKTOK')),
  CHECK (shop_type IN ('STANDARD','MALL')),
  CHECK (price_type IN ('REGULAR','CAMPAIGN','MEGA_CAMPAIGN'))
);

CREATE TABLE "app"."price_control_source_batches" (
  "apply_no" text,
  "country_code" text NOT NULL,
  "approval_status" text NOT NULL,
  "source_row_count" integer NOT NULL DEFAULT 0,
  "batch_fingerprint" text NOT NULL,
  "apply_created_at" timestamptz,
  "submitted_at" timestamptz,
  "approved_at" timestamptz,
  "effective_at" timestamptz NOT NULL,
  "first_seen_at" timestamptz NOT NULL,
  "last_seen_at" timestamptz NOT NULL,
  "last_sync_run_id" text NOT NULL,
  PRIMARY KEY ("apply_no"),
  CHECK (source_row_count >= 0)
);

CREATE TABLE "app"."price_control_sync_runs" (
  "id" text,
  "foundation_source_run_id" text,
  "trigger_type" text NOT NULL,
  "sync_mode" text NOT NULL,
  "status" text NOT NULL,
  "source_version" text,
  "source_checked_at" timestamptz,
  "source_table_updated_at" timestamptz,
  "source_business_updated_at" timestamptz,
  "fetched_at" timestamptz,
  "watermark_at" timestamptz,
  "batches_seen" integer NOT NULL DEFAULT 0,
  "batches_applied" integer NOT NULL DEFAULT 0,
  "source_rows_seen" integer NOT NULL DEFAULT 0,
  "price_points_seen" integer NOT NULL DEFAULT 0,
  "change_count" integer NOT NULL DEFAULT 0,
  "input_fingerprint" text NOT NULL,
  "error_code" text,
  "error_message" text,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "notification_status" text,
  "notified_at" timestamptz,
  "notification_error_code" text,
  PRIMARY KEY ("id"),
  UNIQUE ("foundation_source_run_id"),
  CHECK (trigger_type IN ('manual','scheduled','rehearsal')),
  CHECK (sync_mode IN ('baseline','incremental')),
  CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','PARTIAL_SUCCESS','FAILED','CANCELLED')),
  CHECK (batches_seen >= 0),
  CHECK (batches_applied >= 0),
  CHECK (source_rows_seen >= 0),
  CHECK (price_points_seen >= 0),
  CHECK (change_count >= 0),
  CHECK (notification_status IS NULL OR notification_status IN ('SENT','SKIPPED','FAILED','NOT_CONFIGURED'))
);

CREATE TABLE "app"."product_ai_contents" (
  "id" text,
  "product_sku_id" text NOT NULL,
  "country" text NOT NULL,
  "sku" text NOT NULL,
  "provider" text NOT NULL,
  "model" text NOT NULL,
  "content_type" text NOT NULL DEFAULT 'selling_points_and_scenarios',
  "input_context_json" jsonb NOT NULL,
  "output_content_json" jsonb NOT NULL,
  "prompt_version" text NOT NULL,
  "status" text NOT NULL,
  "version" integer NOT NULL,
  "created_by" text NOT NULL,
  "request_id" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "confirmed_at" timestamptz,
  "confirmed_by" text,
  "archived_at" timestamptz,
  "listing_draft_id" text,
  "platform" text,
  "shop_name" text,
  "context_hash" text,
  "previous_content_id" text,
  "adopted_at" timestamptz,
  "adopted_by" text,
  "adopted_content_json" jsonb,
  "is_manually_modified" integer NOT NULL DEFAULT 0,
  "manual_content_json" jsonb,
  PRIMARY KEY ("id"),
  UNIQUE ("product_sku_id", "content_type", "version"),
  CHECK (status IN ('draft', 'confirmed', 'archived')),
  CHECK (version >= 1)
);

CREATE TABLE "app"."product_categories" (
  "id" text,
  "parent_id" text,
  "parent_key" text NOT NULL,
  "level" integer NOT NULL,
  "source_system" text NOT NULL,
  "source_name" text NOT NULL,
  "normalized_name" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "first_seen_batch_id" text NOT NULL,
  "last_seen_batch_id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "inactive_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "level", "parent_key", "normalized_name"),
  CHECK (level IN (1, 2)),
  CHECK (status IN ('active', 'inactive', 'review_required'))
);

CREATE TABLE "app"."product_cost_snapshots" (
  "id" text,
  "sku_id" text NOT NULL,
  "batch_id" text NOT NULL,
  "country_raw" text,
  "cost_cny" numeric NOT NULL,
  "exchange_rate" numeric NOT NULL,
  "exchange_direction" text NOT NULL,
  "cost_local" numeric NOT NULL,
  "price_tier_20" numeric,
  "price_tier_25" numeric,
  "price_tier_35" numeric,
  "price_tier_45" numeric,
  "attach_rate" numeric,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("sku_id", "batch_id"),
  CHECK (exchange_direction IN ('local_per_cny', 'cny_per_local', 'equivalent'))
);

CREATE TABLE "app"."product_detail_preferences" (
  "scope_key" text,
  "visible_fields_json" jsonb NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "operator_label" text NOT NULL,
  "request_id" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("scope_key"),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_field_override_events" (
  "id" text,
  "sku_id" text NOT NULL,
  "field_code" text NOT NULL,
  "previous_value_json" jsonb,
  "next_value_json" jsonb,
  "operator_label" text NOT NULL,
  "request_id" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "app"."product_field_overrides" (
  "sku_id" text,
  "field_code" text,
  "value_json" jsonb,
  "operator_label" text NOT NULL,
  "request_id" text,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("sku_id", "field_code"),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_identity_mappings" (
  "id" text,
  "source_system" text NOT NULL,
  "source_sku" text NOT NULL,
  "normalized_source_sku" text NOT NULL,
  "platform" text NOT NULL,
  "country_code" text NOT NULL,
  "internal_product_id" text,
  "internal_sku" text,
  "main_sku" text,
  "mapping_status" text NOT NULL,
  "mapping_source" text NOT NULL,
  "confidence" numeric,
  "first_source_batch_id" text,
  "last_source_batch_id" text,
  "confirmed_by" text,
  "confirmed_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "platform", "country_code", "normalized_source_sku"),
  CHECK (mapping_status IN ('matched', 'manually_confirmed', 'ambiguous', 'unmatched', 'revoked')),
  CHECK (mapping_source IN ('exact_country_sku', 'manual', 'unresolved', 'revoked'))
);

CREATE TABLE "app"."product_image_generation_items" (
  "id" text,
  "task_id" text NOT NULL,
  "slot_key" text NOT NULL,
  "slot_type" text NOT NULL,
  "slot_index" integer NOT NULL,
  "label" text NOT NULL,
  "aspect_ratio" text,
  "prompt" text NOT NULL,
  "negative_prompt" text,
  "status" text NOT NULL,
  "generated_file_id" text,
  "error_code" text,
  "error_message" text,
  "adopted_at" timestamptz,
  "adopted_by" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("task_id", "slot_key"),
  CHECK (slot_index >= 0),
  CHECK (status IN ('waiting','generating','completed','failed','cancelled'))
);

CREATE TABLE "app"."product_image_generation_tasks" (
  "id" text,
  "product_sku_id" text NOT NULL,
  "listing_draft_id" text,
  "template_key" text NOT NULL,
  "provider" text,
  "model" text,
  "context_hash" text NOT NULL,
  "context_json" jsonb NOT NULL,
  "prompt_plan_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" text NOT NULL,
  "error_code" text,
  "error_message" text,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "cancelled_at" timestamptz,
  PRIMARY KEY ("id"),
  CHECK (status IN (
    'pending','generating_prompt','waiting_generation','generating',
    'partially_completed','completed','failed','cancelled'
  ))
);

CREATE TABLE "app"."product_images" (
  "id" text,
  "sku_id" text NOT NULL,
  "original_filename" text NOT NULL,
  "storage_filename" text NOT NULL,
  "relative_path" text NOT NULL,
  "mime_type" text NOT NULL,
  "file_size" bigint NOT NULL,
  "file_hash" text NOT NULL,
  "is_primary" integer NOT NULL DEFAULT 0,
  "sort_order" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'available',
  "operator_label" text NOT NULL,
  "request_id" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("relative_path"),
  CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  CHECK (file_size > 0),
  CHECK (is_primary IN (0, 1)),
  CHECK (status IN ('available', 'deleted', 'missing', 'integrity_failed'))
);

CREATE TABLE "app"."product_import_batches" (
  "id" text,
  "source_system" text NOT NULL DEFAULT 'company_product_center',
  "source_period" text,
  "source_country_raw" text,
  "file_sha256" text NOT NULL,
  "header_fingerprint" text,
  "status" text NOT NULL,
  "row_count" integer NOT NULL DEFAULT 0,
  "new_count" integer NOT NULL DEFAULT 0,
  "updated_count" integer NOT NULL DEFAULT 0,
  "unchanged_count" integer NOT NULL DEFAULT 0,
  "conflict_count" integer NOT NULL DEFAULT 0,
  "exception_count" integer NOT NULL DEFAULT 0,
  "blocker_count" integer NOT NULL DEFAULT 0,
  "reminder_count" integer NOT NULL DEFAULT 0,
  "information_count" integer NOT NULL DEFAULT 0,
  "mapping_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "unknown_fields_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "validation_summary_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "operator_label" text NOT NULL,
  "request_id" text,
  "revision" integer NOT NULL DEFAULT 1,
  "error_code" text,
  "error_summary" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "applied_at" timestamptz,
  "cancelled_at" timestamptz,
  "unmatched_count" integer NOT NULL DEFAULT 0,
  "will_write_count" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CHECK (status IN ('uploaded', 'validating', 'preview_ready', 'applying', 'applied', 'validation_failed', 'apply_failed', 'cancelled')),
  CHECK (row_count >= 0),
  CHECK (new_count >= 0),
  CHECK (updated_count >= 0),
  CHECK (unchanged_count >= 0),
  CHECK (conflict_count >= 0),
  CHECK (exception_count >= 0),
  CHECK (blocker_count >= 0),
  CHECK (reminder_count >= 0),
  CHECK (information_count >= 0),
  CHECK (revision >= 1),
  CHECK (unmatched_count >= 0),
  CHECK (will_write_count >= 0)
);

CREATE TABLE "app"."product_import_field_changes" (
  "id" text,
  "import_batch_id" text NOT NULL,
  "import_row_id" text NOT NULL,
  "product_package_row_id" text,
  "source_row_number" integer NOT NULL,
  "country_raw" text,
  "sku_code" text,
  "warehouse_raw" text,
  "chinese_name" text,
  "source_header" text NOT NULL,
  "field_name" text NOT NULL,
  "old_value_json" jsonb,
  "new_value_json" jsonb,
  "old_type" text,
  "new_type" text,
  "has_manual_override" integer NOT NULL DEFAULT 0,
  "changed_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (source_row_number >= 2),
  CHECK (has_manual_override IN (0, 1))
);

CREATE TABLE "app"."product_import_files" (
  "id" text,
  "batch_id" text NOT NULL,
  "export_file_id" text NOT NULL,
  "file_role" text NOT NULL DEFAULT 'source',
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("export_file_id"),
  UNIQUE ("batch_id", "file_role"),
  CHECK (file_role IN ('source', 'error_report', 'diff_export'))
);

CREATE TABLE "app"."product_import_issues" (
  "id" text,
  "batch_id" text NOT NULL,
  "row_id" text,
  "source_row_number" integer,
  "issue_code" text NOT NULL,
  "severity" text NOT NULL,
  "field_code" text,
  "current_value_json" jsonb,
  "suggested_value_json" jsonb,
  "message" text NOT NULL,
  "suggestion" text,
  "status" text NOT NULL DEFAULT 'open',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (severity IN ('blocker', 'reminder', 'information')),
  CHECK (status IN ('open', 'acknowledged', 'resolved', 'ignored'))
);

CREATE TABLE "app"."product_import_rows" (
  "id" text,
  "batch_id" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "source_sku" text,
  "row_sha256" text NOT NULL,
  "raw_payload_json" jsonb NOT NULL,
  "normalized_payload_json" jsonb NOT NULL,
  "validation_codes_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "outcome" text NOT NULL,
  "target_sku_id" text,
  "applied_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "source_country_raw" text,
  "product_key" text,
  "product_sha256" text,
  "source_warehouse_raw" text,
  "source_row_key" text,
  "row_occurrence" integer NOT NULL DEFAULT 1,
  "raw_types_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "package_row_id" text,
  PRIMARY KEY ("id"),
  UNIQUE ("batch_id", "source_row_number"),
  CHECK (source_row_number >= 2),
  CHECK (outcome IN ('new', 'updated', 'unchanged', 'conflict', 'exception')),
  CHECK (row_occurrence >= 1)
);

CREATE TABLE "app"."product_inventory_snapshots" (
  "id" text,
  "sku_id" text NOT NULL,
  "batch_id" text NOT NULL,
  "warehouse_raw" text NOT NULL,
  "warehouse_stock" numeric,
  "planned_warehouse_raw" text,
  "captured_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("sku_id", "batch_id", "warehouse_raw")
);

CREATE TABLE "app"."product_listing_drafts" (
  "id" text,
  "product_sku_id" text NOT NULL,
  "country" text NOT NULL,
  "sku" text NOT NULL,
  "platform" text NOT NULL,
  "shop_id" text,
  "shop_key" text NOT NULL,
  "shop_name" text,
  "marketplace" text,
  "platform_category_id" text,
  "platform_category_name" text,
  "listing_mode" text NOT NULL DEFAULT 'standard',
  "title" text,
  "subtitle" text,
  "description" text,
  "search_keywords_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "brand" text,
  "model" text,
  "target_users" text,
  "content_language" text NOT NULL DEFAULT '中文',
  "selling_points_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "usage_scenarios_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "platform_attributes_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "variants_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "pricing_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "media_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "logistics_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "compliance_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" text NOT NULL DEFAULT 'draft',
  "validation_result_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "revision" integer NOT NULL DEFAULT 1,
  "created_by" text NOT NULL,
  "updated_by" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  "country_code" text,
  "country_name" text,
  "marketplace_code" text,
  "product_positioning" text,
  "content_style" text,
  "price_positioning" text,
  "primary_scenarios" text,
  "special_requirements" text,
  "forbidden_content" text,
  "ai_context_hash" text,
  "ai_adoptions_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY ("id"),
  CHECK (platform IN ('shopee', 'lazada', 'tiktok_shop')),
  CHECK (status IN ('draft', 'ready', 'publishing', 'published', 'failed', 'archived')),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_listing_publish_records" (
  "id" text,
  "listing_draft_id" text NOT NULL,
  "platform" text NOT NULL,
  "shop_id" text,
  "request_payload_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "response_payload_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "platform_product_id" text,
  "platform_listing_id" text,
  "publish_status" text NOT NULL,
  "error_code" text,
  "error_message" text,
  "published_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (publish_status IN ('pending', 'publishing', 'published', 'failed', 'cancelled'))
);

CREATE TABLE "app"."product_media_assets" (
  "id" text,
  "source_system" text NOT NULL,
  "source_url" text,
  "storage_file_id" text NOT NULL,
  "original_filename" text NOT NULL,
  "storage_filename" text NOT NULL,
  "relative_path" text NOT NULL,
  "sha256" text NOT NULL,
  "mime_type" text NOT NULL,
  "width" integer NOT NULL,
  "height" integer NOT NULL,
  "file_size" bigint NOT NULL,
  "status" text NOT NULL DEFAULT 'available',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("sha256"),
  UNIQUE ("relative_path"),
  UNIQUE ("storage_file_id"),
  CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  CHECK (width > 0),
  CHECK (height > 0),
  CHECK (file_size > 0),
  CHECK (status IN ('available', 'missing', 'integrity_failed', 'deleted'))
);

CREATE TABLE "app"."product_media_links" (
  "id" text,
  "asset_id" text NOT NULL,
  "source_sku" text NOT NULL,
  "source_sku_normalized" text NOT NULL,
  "product_id" text NOT NULL,
  "country_code" text NOT NULL DEFAULT '',
  "media_role" text NOT NULL DEFAULT 'gallery',
  "mapping_status" text NOT NULL DEFAULT 'suggested',
  "linked_at" timestamptz NOT NULL,
  "linked_by" text NOT NULL,
  "confirmed_at" timestamptz,
  "confirmed_by" text,
  PRIMARY KEY ("id"),
  UNIQUE ("asset_id", "product_id"),
  CHECK (media_role IN ('gallery', 'suggested_primary', 'primary')),
  CHECK (mapping_status IN ('suggested', 'confirmed', 'rejected', 'invalid'))
);

CREATE TABLE "app"."product_models" (
  "id" text,
  "source_system" text NOT NULL,
  "source_main_sku" text NOT NULL,
  "category_id" text NOT NULL,
  "canonical_name" text,
  "identity_status" text NOT NULL DEFAULT 'confirmed',
  "first_seen_batch_id" text NOT NULL,
  "last_seen_batch_id" text NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "inactive_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "source_main_sku"),
  CHECK (identity_status IN ('confirmed', 'review_required', 'inactive')),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_package_rows" (
  "id" text,
  "source_system" text NOT NULL DEFAULT 'company_product_center',
  "source_row_key" text NOT NULL,
  "product_key" text NOT NULL,
  "country_normalized" text NOT NULL,
  "sku_normalized" text NOT NULL,
  "warehouse_normalized" text NOT NULL,
  "row_occurrence" integer NOT NULL,
  "source_row_sha256" text NOT NULL,
  "semantic_row_sha256" text NOT NULL,
  "raw_payload_json" jsonb NOT NULL,
  "raw_types_json" jsonb NOT NULL,
  "normalized_payload_json" jsonb NOT NULL,
  "raw_source_period_json" jsonb,
  "raw_sku_code_json" jsonb,
  "raw_product_name_json" jsonb,
  "raw_main_sku_code_json" jsonb,
  "raw_country_raw_json" jsonb,
  "raw_category_l1_json" jsonb,
  "raw_category_l2_json" jsonb,
  "raw_source_created_date_json" jsonb,
  "raw_new_product_month_json" jsonb,
  "raw_new_product_age_months_json" jsonb,
  "raw_gift_raw_json" jsonb,
  "raw_source_status_json" jsonb,
  "raw_style_code_json" jsonb,
  "raw_style_name_json" jsonb,
  "raw_sales_spec_json" jsonb,
  "raw_item_dimensions_raw_json" jsonb,
  "raw_item_net_weight_g_json" jsonb,
  "raw_item_gross_weight_g_json" jsonb,
  "raw_carton_length_cm_json" jsonb,
  "raw_carton_width_cm_json" jsonb,
  "raw_carton_height_cm_json" jsonb,
  "raw_carton_quantity_json" jsonb,
  "raw_shipping_method_json" jsonb,
  "raw_warehouse_raw_json" jsonb,
  "raw_warehouse_stock_json" jsonb,
  "raw_planned_warehouse_raw_json" jsonb,
  "raw_cost_cny_json" jsonb,
  "raw_exchange_rate_json" jsonb,
  "raw_cost_local_json" jsonb,
  "raw_price_tier_20_json" jsonb,
  "raw_price_tier_25_json" jsonb,
  "raw_price_tier_35_json" jsonb,
  "raw_price_tier_45_json" jsonb,
  "raw_attach_rate_json" jsonb,
  "raw_forecast_daily_sales_json" jsonb,
  "import_batch_id" text NOT NULL,
  "source_row_number" integer NOT NULL,
  "first_seen_batch_id" text NOT NULL,
  "latest_batch_id" text NOT NULL,
  "latest_import_row_id" text NOT NULL,
  "latest_source_row_number" integer NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "source_row_key"),
  CHECK (row_occurrence >= 1),
  CHECK (source_row_number >= 2),
  CHECK (latest_source_row_number >= 2),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_packaging_profiles" (
  "sku_id" text,
  "source_row_id" text NOT NULL,
  "item_dimensions_raw" text,
  "item_net_weight_g" numeric,
  "item_gross_weight_g" numeric,
  "carton_length_cm" numeric,
  "carton_width_cm" numeric,
  "carton_height_cm" numeric,
  "carton_quantity" integer,
  "shipping_method" text,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("sku_id")
);

CREATE TABLE "app"."product_price_change_events" (
  "id" text,
  "sync_run_id" text NOT NULL,
  "source_apply_no" text NOT NULL,
  "price_key" text NOT NULL,
  "country_code" text NOT NULL,
  "category_name" text,
  "sku" text NOT NULL,
  "product_name_cn" text,
  "platform" text NOT NULL,
  "shop_type" text NOT NULL,
  "price_type" text NOT NULL,
  "old_price" text,
  "new_price" text,
  "delta_value" text,
  "delta_percent" double precision,
  "direction" text NOT NULL,
  "change_text" text NOT NULL,
  "change_fingerprint" text NOT NULL,
  "foundation_task_id" text,
  "detected_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("change_fingerprint"),
  CHECK (platform IN ('LAZADA','SHOPEE','TIKTOK')),
  CHECK (shop_type IN ('STANDARD','MALL')),
  CHECK (price_type IN ('REGULAR','CAMPAIGN','MEGA_CAMPAIGN')),
  CHECK (direction IN ('UP','DOWN','NEW','REMOVED'))
);

CREATE TABLE "app"."product_sku_current_prices" (
  "price_key" text,
  "country_code" text NOT NULL,
  "category_name" text,
  "sku" text NOT NULL,
  "product_name_cn" text,
  "sku_status" text,
  "platform" text NOT NULL,
  "shop_type" text NOT NULL,
  "price_type" text NOT NULL,
  "price_value" text NOT NULL,
  "source_apply_no" text NOT NULL,
  "source_snapshot_id" text NOT NULL,
  "effective_at" timestamptz NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("price_key"),
  CHECK (platform IN ('LAZADA','SHOPEE','TIKTOK')),
  CHECK (shop_type IN ('STANDARD','MALL')),
  CHECK (price_type IN ('REGULAR','CAMPAIGN','MEGA_CAMPAIGN')),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."product_sku_lifecycle" (
  "sku_id" text,
  "status_code" text NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "decision_source" text NOT NULL,
  "source_status_raw" text,
  "source_batch_id" text NOT NULL,
  "reason_code" text NOT NULL,
  "operator_label" text NOT NULL,
  "request_id" text,
  "effective_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("sku_id"),
  CHECK (status_code IN ('ACTIVE', 'NEW', 'CLEARANCE', 'DISCONTINUED', 'ARCHIVED')),
  CHECK (revision >= 1),
  CHECK (decision_source IN ('central', 'manual', 'rule'))
);

CREATE TABLE "app"."product_sku_lifecycle_events" (
  "id" text,
  "sku_id" text NOT NULL,
  "from_status_code" text,
  "to_status_code" text NOT NULL,
  "decision_source" text NOT NULL,
  "source_batch_id" text NOT NULL,
  "reason_code" text NOT NULL,
  "operator_label" text NOT NULL,
  "request_id" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CHECK (to_status_code IN ('ACTIVE', 'NEW', 'CLEARANCE', 'DISCONTINUED', 'ARCHIVED')),
  CHECK (decision_source IN ('central', 'manual', 'rule'))
);

CREATE TABLE "app"."product_skus" (
  "id" text,
  "source_system" text NOT NULL,
  "source_sku" text NOT NULL,
  "normalized_sku" text NOT NULL,
  "category_id" text NOT NULL,
  "model_id" text,
  "source_product_name" text NOT NULL,
  "source_main_sku" text,
  "source_style_code" text,
  "source_style_name" text,
  "source_sales_spec" text,
  "source_status_raw" text NOT NULL,
  "current_source_row_id" text NOT NULL,
  "first_seen_batch_id" text NOT NULL,
  "last_seen_batch_id" text NOT NULL,
  "revision" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "archived_at" timestamptz,
  "country_raw" text NOT NULL DEFAULT '',
  "sku_code_normalized" text NOT NULL DEFAULT '',
  "deleted_at" timestamptz,
  "deleted_by" text,
  "delete_reason" text,
  "restored_at" timestamptz,
  "restored_by" text,
  PRIMARY KEY ("id"),
  UNIQUE ("source_system", "normalized_sku"),
  CHECK (revision >= 1)
);

CREATE TABLE "app"."scheduled_export_run_events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "run_id" text NOT NULL,
  "stage" text NOT NULL,
  "status" text NOT NULL,
  "attempt" integer NOT NULL DEFAULT 1,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "duration_ms" integer,
  "message" text,
  "error_code" text,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "app"."scheduled_export_runs" (
  "id" text,
  "task_id" text NOT NULL,
  "trigger_type" text NOT NULL,
  "scheduled_run_at" timestamptz NOT NULL,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "status" text NOT NULL,
  "payment_start_date" date,
  "payment_end_date" date,
  "raw_order_count" integer NOT NULL DEFAULT 0,
  "filtered_order_count" integer NOT NULL DEFAULT 0,
  "detail_row_count" integer NOT NULL DEFAULT 0,
  "export_file_id" text,
  "notification_status" text,
  "retry_count" integer NOT NULL DEFAULT 0,
  "error_stage" text,
  "error_code" text,
  "error_message" text,
  "log_summary_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("task_id", "scheduled_run_at")
);

CREATE TABLE "app"."scheduled_export_tasks" (
  "id" text,
  "task_type" text NOT NULL DEFAULT 'order_export',
  "name" text NOT NULL,
  "description" text,
  "account_profile_id" text NOT NULL,
  "dingtalk_config_id" text,
  "schedule_type" text NOT NULL,
  "schedule_config_json" jsonb NOT NULL,
  "timezone" text NOT NULL DEFAULT 'Asia/Shanghai',
  "payment_date_mode" text NOT NULL,
  "payment_date_config_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "filters_json" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "enabled" integer NOT NULL DEFAULT 1,
  "file_retention_days" integer,
  "notify_enabled" integer NOT NULL DEFAULT 1,
  "catch_up_enabled" integer NOT NULL DEFAULT 1,
  "last_run_at" timestamptz,
  "last_run_status" text,
  "next_run_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  "deleted_by" text,
  "delete_reason" text,
  PRIMARY KEY ("id"),
  CHECK (deleted_by IS NULL OR length(deleted_by) <= 64),
  CHECK (delete_reason IS NULL OR length(delete_reason) <= 240)
);

CREATE TABLE "app"."scheduler_leases" (
  "name" text,
  "owner_id" text NOT NULL,
  "lease_until" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("name")
);

CREATE TABLE "app"."schema_migrations" (
  "version" text,
  "applied_at" timestamptz NOT NULL,
  PRIMARY KEY ("version")
);
