CREATE TABLE IF NOT EXISTS app.fulfillment_previews (
  id text PRIMARY KEY,
  status text NOT NULL,
  shop_id text NOT NULL,
  shop_name text NOT NULL,
  channel_id text NOT NULL,
  channel_name text NOT NULL,
  confirmation_hash text NOT NULL,
  expires_at text NOT NULL,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.fulfillment_preview_orders (
  preview_id text NOT NULL REFERENCES app.fulfillment_previews(id) ON DELETE CASCADE,
  order_key text NOT NULL,
  display_order_id text NOT NULL,
  trade_number text,
  warehouse text,
  sku_count integer NOT NULL DEFAULT 0,
  eligible integer NOT NULL,
  exclusion_json text NOT NULL DEFAULT '[]',
  snapshot_json text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  PRIMARY KEY (preview_id, order_key)
);

CREATE TABLE IF NOT EXISTS app.fulfillment_batches (
  id text PRIMARY KEY,
  preview_id text NOT NULL UNIQUE REFERENCES app.fulfillment_previews(id),
  status text NOT NULL,
  created_at text NOT NULL,
  finished_at text,
  timings_json text
);

CREATE TABLE IF NOT EXISTS app.fulfillment_batch_orders (
  batch_id text NOT NULL REFERENCES app.fulfillment_batches(id) ON DELETE CASCADE,
  order_key text NOT NULL,
  display_order_id text NOT NULL,
  status text NOT NULL,
  tracking_number_masked text,
  error_code text,
  error_message text,
  before_status text,
  after_status text,
  timings_json text,
  updated_at text NOT NULL,
  PRIMARY KEY (batch_id, order_key)
);

CREATE TABLE IF NOT EXISTS app.fulfillment_idempotency (
  order_key text PRIMARY KEY,
  batch_id text NOT NULL,
  status text NOT NULL,
  completed_at text
);

CREATE TABLE IF NOT EXISTS app.fulfillment_scan_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at text NOT NULL,
  finished_at text NOT NULL,
  outcome text NOT NULL,
  message text NOT NULL,
  eligible_count integer NOT NULL DEFAULT 0,
  excluded_count integer NOT NULL DEFAULT 0,
  preview_id text
);

CREATE TABLE IF NOT EXISTS app.fulfillment_manual_recovery_checks (
  order_key text PRIMARY KEY,
  batch_id text NOT NULL,
  pass_count integer NOT NULL DEFAULT 0,
  first_passed_at text NOT NULL,
  last_passed_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.fulfillment_tracking_recoveries (
  order_key text PRIMARY KEY,
  batch_id text NOT NULL,
  display_order_id text NOT NULL,
  shop_id text NOT NULL,
  status text NOT NULL,
  submitted_at text NOT NULL,
  next_check_at text NOT NULL,
  deadline_at text NOT NULL,
  last_checked_at text,
  reset_count integer NOT NULL DEFAULT 0,
  last_reset_at text,
  last_error_code text,
  last_error_message text,
  completed_at text
);

CREATE TABLE IF NOT EXISTS app.fulfillment_agent_runs (
  id text PRIMARY KEY,
  conversation_id text NOT NULL,
  status text NOT NULL,
  model text NOT NULL,
  step_count integer NOT NULL DEFAULT 0,
  tool_trace_json text NOT NULL DEFAULT '[]',
  error_code text,
  started_at text NOT NULL,
  finished_at text
);

CREATE INDEX IF NOT EXISTS idx_fulfillment_previews_pending
  ON app.fulfillment_previews(status, shop_id, expires_at, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fulfillment_batches_status
  ON app.fulfillment_batches(status, created_at);
CREATE INDEX IF NOT EXISTS idx_fulfillment_batch_orders_status
  ON app.fulfillment_batch_orders(status, error_code, updated_at);
CREATE INDEX IF NOT EXISTS idx_fulfillment_tracking_due
  ON app.fulfillment_tracking_recoveries(status, next_check_at, shop_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_scan_runs_started
  ON app.fulfillment_scan_runs(started_at DESC);

