import type {
  CountryMappingRow,
  MetricSummary,
  OperationTask,
  OpportunityCell,
  ProductInsight,
  ReadinessItem,
  ShopMappingRow,
  StoreSummary,
  TrendSeries,
} from "./types";

export const metrics: MetricSummary[] = [
  {
    key: "must-do",
    label: "今日必须关注",
    value: 8,
    delta: 2,
    tone: "danger",
    description: "按优先级收敛后的店长任务",
    targetView: "today",
  },
  {
    key: "stores",
    label: "需处理店铺",
    value: 12,
    delta: 3,
    tone: "warning",
    description: "存在 P0 / P1 活动任务",
    targetView: "stores",
  },
  {
    key: "growth",
    label: "确定性增长候选",
    value: 23,
    delta: 5,
    tone: "positive",
    description: "规则证据完整且库存可支撑",
    targetView: "products",
  },
  {
    key: "blocked",
    label: "数据阻塞项",
    value: 4,
    tone: "info",
    description: "配置或历史窗口尚未满足",
    targetView: "settings",
  },
];

export const readinessItems: ReadinessItem[] = [
  {
    key: "history",
    label: "有效订单历史窗口",
    current: 7,
    target: 14,
    unit: "天",
    state: "PARTIAL",
    detail: "只有 2026-07-15 至 2026-07-21 一段完整窗口。",
    nextAction: "继续每日同步，满 14 个完整业务日后启用趋势任务。",
  },
  {
    key: "shops",
    label: "店铺身份与店长归属",
    current: 0,
    target: 107,
    unit: "家",
    state: "BLOCKED",
    detail: "107 家来源店铺均处于待审核状态。",
    nextAction: "确认内部店铺、国家和店长归属。",
  },
  {
    key: "warehouses",
    label: "仓库国家映射",
    current: 0,
    target: 27,
    unit: "个",
    state: "BLOCKED",
    detail: "最新库存快照涉及 27 个仓库，尚未发布国家映射。",
    nextAction: "由用户维护并发布带版本的仓库国家配置。",
  },
  {
    key: "forecast",
    label: "预测日销量语义",
    current: 0,
    target: 1,
    unit: "项",
    state: "BLOCKED",
    detail: "20,020 条快照仍标记为语义未确认。",
    nextAction: "确认该字段只作为来源预测参考，不称为公司实际销量。",
  },
];

export const demoTasks: OperationTask[] = [
  {
    id: "task-001",
    priority: "P1",
    type: "STORE_ASSORTMENT_GAP",
    title: "补齐菲律宾 Shopee 太阳能高表现货盘",
    discovery: "来源高表现 Top20 SKU 中，本店近 28 天只观察到 5 个 SKU 产生有效订单。",
    recommendation: "先核查 12 个 SKU 的在线状态，再选择 3–5 个进行低风险测试。",
    shopName: "PH Solar Hub",
    countryCode: "PH",
    countryName: "菲律宾",
    platform: "SHOPEE",
    manager: "张敏",
    category: "太阳能",
    skuCount: 12,
    status: "NEW",
    firstSeen: "2026-07-25 08:30",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "来源高表现 SKU", value: "20 个", detail: "类目内预测日销量 P80 以上" },
      { label: "近 28 天有效销售 SKU", value: "5 个" },
      { label: "库存可支撑", value: "12 个" },
    ],
  },
  {
    id: "task-002",
    priority: "P1",
    type: "SALES_DECLINE",
    title: "复核印尼 TikTok 工具类销售下滑",
    discovery: "店铺工具类当前 7 天有效订单销量较前 7 天下滑 28.6%。",
    recommendation: "检查 Top5 下滑 SKU 的流量、价格和在线状态，记录处理结果后进入观察。",
    shopName: "ID Tool Works",
    countryCode: "ID",
    countryName: "印尼",
    platform: "TIKTOK",
    manager: "李桐",
    category: "工具",
    skuCount: 5,
    status: "ACKNOWLEDGED",
    firstSeen: "2026-07-26 08:25",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "当前 7 天", value: "125 件" },
      { label: "前 7 天", value: "175 件" },
      { label: "变化", value: "-28.6%" },
    ],
  },
  {
    id: "task-003",
    priority: "P1",
    type: "INVENTORY_RISK",
    title: "处理泰国汽车用品缺货风险",
    discovery: "3 个高承接 SKU 的可售天数低于 7 天，其中 1 个已接近断货。",
    recommendation: "核对在途到仓时间并调整推广节奏，不能自动触发补货。",
    shopName: "TH Auto Lab",
    countryCode: "TH",
    countryName: "泰国",
    platform: "LAZADA",
    manager: "张敏",
    category: "汽车用品",
    skuCount: 3,
    status: "IN_PROGRESS",
    firstSeen: "2026-07-24 08:33",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "最低可售天数", value: "2 天" },
      { label: "近 28 天有效订单", value: "364 件" },
      { label: "在途量", value: "880 件" },
    ],
  },
  {
    id: "task-004",
    priority: "P2",
    type: "QUIET_ENTRY",
    title: "核查菲律宾家居蓝海候选",
    discovery: "8 个 SKU 来源预测表现位于类目 P80 以上、库存充足，但本店近 28 天未观察到有效订单。",
    recommendation: "核查在线状态后，选择 2–3 个 SKU 进行低风险测试。",
    shopName: "PH Home Select",
    countryCode: "PH",
    countryName: "菲律宾",
    platform: "LAZADA",
    manager: "王澄",
    category: "家居",
    skuCount: 8,
    status: "NEW",
    firstSeen: "2026-07-27 08:31",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "类目 P80+ SKU", value: "8 个" },
      { label: "近 28 天有效订单", value: "0 件" },
      { label: "平均可售天数", value: "74 天" },
    ],
  },
  {
    id: "task-005",
    priority: "P2",
    type: "NEW_PRODUCT",
    title: "跟进越南灯具新品观察组",
    discovery: "90 天新品池有 14 个 SKU 已产生销售，其中 4 个连续两周增长。",
    recommendation: "保留现有动作并观察 7 天，避免因短期波动提前扩大。",
    shopName: "VN Light Studio",
    countryCode: "VN",
    countryName: "越南",
    platform: "SHOPEE",
    manager: "赵岚",
    category: "灯具",
    skuCount: 4,
    status: "MONITORING",
    firstSeen: "2026-07-23 08:28",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "新品观察池", value: "14 个" },
      { label: "连续增长", value: "4 个" },
      { label: "当前 7 天", value: "89 件" },
    ],
  },
  {
    id: "task-006",
    priority: "P2",
    type: "CROSS_COUNTRY_CANDIDATE",
    title: "核查太阳能 SKU 的跨国候选",
    discovery: "SKU S2SN3001199 在泰国表现稳定，菲律宾同国家货盘预测较强但本店承接低。",
    recommendation: "核查菲律宾在线状态和合规限制后，再决定是否低风险测试。",
    shopName: "PH Solar Hub",
    countryCode: "PH",
    countryName: "菲律宾",
    platform: "SHOPEE",
    manager: "张敏",
    category: "太阳能",
    skuCount: 1,
    status: "NEW",
    firstSeen: "2026-07-27 08:31",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "泰国当前 7 天", value: "142 件" },
      { label: "菲律宾来源预测", value: "541 件/日" },
      { label: "菲律宾近 28 天", value: "3 件" },
    ],
  },
  {
    id: "task-007",
    priority: "P3",
    type: "SALES_DECLINE",
    title: "观察马来西亚家居类轻度波动",
    discovery: "当前 7 天较前 7 天下滑 8.3%，尚未达到高优先级门槛。",
    recommendation: "保持观察，不执行自动经营动作。",
    shopName: "MY Home Plus",
    countryCode: "MY",
    countryName: "马来西亚",
    platform: "LAZADA",
    manager: "王澄",
    category: "家居",
    skuCount: 3,
    status: "MONITORING",
    firstSeen: "2026-07-26 08:25",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "当前 7 天", value: "110 件" },
      { label: "前 7 天", value: "120 件" },
      { label: "变化", value: "-8.3%" },
    ],
  },
  {
    id: "task-008",
    priority: "P3",
    type: "DATA_CONFIGURATION",
    title: "确认 2 个新增仓库的国家映射",
    discovery: "新增仓库尚未进入已发布国家映射版本，相关机会信号已被阻断。",
    recommendation: "由有权限的用户确认国家映射并发布新配置版本。",
    shopName: "配置中心",
    countryCode: "UNMAPPED",
    countryName: "待确认",
    platform: "UNMAPPED",
    manager: "数据管理员",
    category: "配置",
    skuCount: 0,
    status: "BLOCKED",
    firstSeen: "2026-07-27 08:31",
    lastHit: "2026-07-27 08:31",
    evidence: [
      { label: "待映射仓库", value: "2 个" },
      { label: "受阻库存行", value: "486 行" },
      { label: "配置版本", value: "未发布" },
    ],
    blockedReason: "缺少仓库国家映射",
  },
];

export const readinessTasks: OperationTask[] = readinessItems.map((item, index) => ({
  id: `readiness-${item.key}`,
  priority: item.state === "BLOCKED" ? "P1" : "P3",
  type: "DATA_CONFIGURATION",
  title: item.label,
  discovery: item.detail,
  recommendation: item.nextAction,
  shopName: "数据准备",
  countryCode: "UNMAPPED",
  countryName: "待确认",
  platform: "UNMAPPED",
  manager: "数据管理员",
  category: "数据门禁",
  skuCount: 0,
  status: item.state === "BLOCKED" ? "BLOCKED" : "MONITORING",
  firstSeen: "2026-07-27 08:31",
  lastHit: "2026-07-27 08:31",
  evidence: [
    { label: "当前", value: `${item.current}${item.unit}` },
    { label: "目标", value: `${item.target}${item.unit}` },
    { label: "完成度", value: `${Math.round((item.current / item.target) * 100)}%` },
  ],
  blockedReason: item.state === "BLOCKED" ? item.detail : undefined,
})) as OperationTask[];

export const stores: StoreSummary[] = [
  {
    id: "store-ph-solar",
    shopName: "PH Solar Hub",
    countryCode: "PH",
    countryName: "菲律宾",
    platform: "SHOPEE",
    manager: "张敏",
    current7d: 186,
    previous7d: 149,
    trendPercent: 24.8,
    trendState: "GROWING",
    highPerformanceCoverage: 25,
    activeTaskCount: 3,
    severeAnomalyCount: 1,
    state: "ACTION_REQUIRED",
    updatedAt: "2026-07-27 08:31",
  },
  {
    id: "store-th-auto",
    shopName: "TH Auto Lab",
    countryCode: "TH",
    countryName: "泰国",
    platform: "LAZADA",
    manager: "张敏",
    current7d: 245,
    previous7d: 232,
    trendPercent: 5.6,
    trendState: "STABLE",
    highPerformanceCoverage: 63,
    activeTaskCount: 2,
    severeAnomalyCount: 1,
    state: "ACTION_REQUIRED",
    updatedAt: "2026-07-27 08:31",
  },
  {
    id: "store-id-tools",
    shopName: "ID Tool Works",
    countryCode: "ID",
    countryName: "印尼",
    platform: "TIKTOK",
    manager: "李桐",
    current7d: 125,
    previous7d: 175,
    trendPercent: -28.6,
    trendState: "DECLINING",
    highPerformanceCoverage: 48,
    activeTaskCount: 2,
    severeAnomalyCount: 1,
    state: "ACTION_REQUIRED",
    updatedAt: "2026-07-27 08:31",
  },
  {
    id: "store-vn-light",
    shopName: "VN Light Studio",
    countryCode: "VN",
    countryName: "越南",
    platform: "SHOPEE",
    manager: "赵岚",
    current7d: 89,
    previous7d: 62,
    trendPercent: 43.5,
    trendState: "GROWING",
    highPerformanceCoverage: 57,
    activeTaskCount: 1,
    severeAnomalyCount: 0,
    state: "WATCH",
    updatedAt: "2026-07-27 08:31",
  },
  {
    id: "store-ph-home",
    shopName: "PH Home Select",
    countryCode: "PH",
    countryName: "菲律宾",
    platform: "LAZADA",
    manager: "王澄",
    current7d: 64,
    previous7d: 58,
    trendPercent: 10.3,
    trendState: "GROWING",
    highPerformanceCoverage: 18,
    activeTaskCount: 1,
    severeAnomalyCount: 0,
    state: "WATCH",
    updatedAt: "2026-07-27 08:31",
  },
  {
    id: "store-my-home",
    shopName: "MY Home Plus",
    countryCode: "MY",
    countryName: "马来西亚",
    platform: "LAZADA",
    manager: "王澄",
    current7d: 110,
    previous7d: 120,
    trendPercent: -8.3,
    trendState: "STABLE",
    highPerformanceCoverage: 72,
    activeTaskCount: 1,
    severeAnomalyCount: 0,
    state: "STABLE",
    updatedAt: "2026-07-27 08:31",
  },
];

const countries = {
  TH: "泰国",
  PH: "菲律宾",
  ID: "印尼",
  VN: "越南",
  MY: "马来西亚",
} as const;

const categories = ["太阳能", "家居", "工具", "灯具", "汽车用品"];
const opportunityMatrix = [
  [18, 9, 7, 4, 12],
  [16, 14, 6, 5, 3],
  [11, 7, 15, 10, 5],
  [9, 8, 13, 12, 4],
  [7, 10, 6, 5, 3],
];

export const opportunityCells: OpportunityCell[] = (
  Object.keys(countries) as Array<keyof typeof countries>
).flatMap((countryCode, countryIndex) =>
  categories.map((category, categoryIndex) => {
    const opportunityCount = opportunityMatrix[countryIndex][categoryIndex];
    return {
      countryCode,
      countryName: countries[countryCode],
      category,
      opportunityCount,
      highPerformanceSkuCount: opportunityCount + 7,
      lowCaptureSkuCount: Math.max(2, opportunityCount - 2),
      inventoryReadySkuCount: Math.max(1, opportunityCount - 4),
    };
  }),
);

export const products: ProductInsight[] = [
  {
    key: "T3GG1200434-PH",
    rank: 1,
    sku: "T3GG1200434",
    name: "折叠收纳置物架",
    countryCode: "PH",
    countryName: "菲律宾",
    category: "家居",
    predictedDailySales: 987,
    ownSales28d: 12,
    current7d: 5,
    previous7d: 3,
    captureRatio: 0.012,
    available: 3120,
    inbound: 460,
    coverageDays: 60,
    direction: "QUIET_ENTRY",
    marketPercentile: 98,
    trendState: "GROWING",
    trendPercent: 66.7,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "S2SN3001199-TH",
    rank: 2,
    sku: "S2SN3001199",
    name: "太阳能庭院灯",
    countryCode: "TH",
    countryName: "泰国",
    category: "太阳能",
    predictedDailySales: 1256,
    ownSales28d: 312,
    current7d: 142,
    previous7d: 108,
    captureRatio: 0.248,
    available: 4270,
    inbound: 1280,
    coverageDays: 45,
    direction: "DEFEND_WINNER",
    marketPercentile: 99,
    trendState: "GROWING",
    trendPercent: 31.5,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "P2DD0020938-TH",
    rank: 3,
    sku: "P2DD0020938",
    name: "车载应急照明套件",
    countryCode: "TH",
    countryName: "泰国",
    category: "汽车用品",
    predictedDailySales: 654,
    ownSales28d: 180,
    current7d: 68,
    previous7d: 72,
    captureRatio: 0.275,
    available: 390,
    inbound: 880,
    coverageDays: 6,
    direction: "SUPPLY_CONSTRAINED",
    marketPercentile: 94,
    trendState: "STABLE",
    trendPercent: -5.6,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "A1AU9002211-VN",
    rank: 4,
    sku: "A1AU9002211",
    name: "多功能电动工具套装",
    countryCode: "VN",
    countryName: "越南",
    category: "工具",
    predictedDailySales: 723,
    ownSales28d: 95,
    current7d: 46,
    previous7d: 31,
    captureRatio: 0.131,
    available: 650,
    inbound: 1400,
    coverageDays: 6,
    direction: "SUPPLY_CONSTRAINED",
    marketPercentile: 95,
    trendState: "GROWING",
    trendPercent: 48.4,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "L5LG4500777-ID",
    rank: 5,
    sku: "L5LG4500777",
    name: "户外壁灯组合装",
    countryCode: "ID",
    countryName: "印尼",
    category: "灯具",
    predictedDailySales: 864,
    ownSales28d: 210,
    current7d: 62,
    previous7d: 88,
    captureRatio: 0.243,
    available: 1860,
    inbound: 360,
    coverageDays: 28,
    direction: "PRIORITY_GROWTH",
    marketPercentile: 96,
    trendState: "DECLINING",
    trendPercent: -29.5,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "W2WD3300110-ID",
    rank: 6,
    sku: "W2WD3300110",
    name: "太阳能监控补光灯",
    countryCode: "ID",
    countryName: "印尼",
    category: "太阳能",
    predictedDailySales: 541,
    ownSales28d: 0,
    current7d: 0,
    previous7d: 0,
    captureRatio: 0,
    available: 2380,
    inbound: 200,
    coverageDays: 90,
    direction: "QUIET_ENTRY",
    marketPercentile: 92,
    trendState: "INSUFFICIENT_HISTORY",
    trendPercent: null,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "H1HM7700331-PH",
    rank: 7,
    sku: "H1HM7700331",
    name: "感应橱柜灯",
    countryCode: "PH",
    countryName: "菲律宾",
    category: "灯具",
    predictedDailySales: 598,
    ownSales28d: 3,
    current7d: 3,
    previous7d: 0,
    captureRatio: 0.005,
    available: 3530,
    inbound: 0,
    coverageDays: 35,
    direction: "QUIET_ENTRY",
    marketPercentile: 93,
    trendState: "NEWLY_SELLING",
    trendPercent: null,
    sourceLabel: "马帮来源预测日销量",
  },
  {
    key: "K8KT5500222-MY",
    rank: 8,
    sku: "K8KT5500222",
    name: "厨房密封收纳盒",
    countryCode: "MY",
    countryName: "马来西亚",
    category: "家居",
    predictedDailySales: 489,
    ownSales28d: 68,
    current7d: 25,
    previous7d: 27,
    captureRatio: 0.139,
    available: 1460,
    inbound: 300,
    coverageDays: 22,
    direction: "DEFEND_WINNER",
    marketPercentile: 90,
    trendState: "STABLE",
    trendPercent: -7.4,
    sourceLabel: "马帮来源预测日销量",
  },
];

export const trendSeries: TrendSeries = {
  dates: ["07-15", "07-16", "07-17", "07-18", "07-19", "07-20", "07-21"],
  previous: [112, 106, 120, 98, 131, 125, 117],
  current: [128, 141, 136, 152, 147, 166, 159],
};

export const countryMappings: CountryMappingRow[] = [
  { key: "warehouse-01", warehouseName: "泰国一号仓", status: "UNMAPPED" },
  { key: "warehouse-02", warehouseName: "菲律宾马尼拉仓", status: "UNMAPPED" },
  { key: "warehouse-03", warehouseName: "印尼雅加达仓", status: "UNMAPPED" },
  { key: "warehouse-04", warehouseName: "越南胡志明仓", status: "UNMAPPED" },
  { key: "warehouse-05", warehouseName: "马来西亚吉隆坡仓", status: "UNMAPPED" },
];

export const shopMappings: ShopMappingRow[] = [
  {
    key: "shop-map-01",
    sourceShopName: "来源店铺 001",
    platform: "LAZADA",
    status: "UNMAPPED",
  },
  {
    key: "shop-map-02",
    sourceShopName: "来源店铺 002",
    platform: "LAZADA",
    status: "UNMAPPED",
  },
  {
    key: "shop-map-03",
    sourceShopName: "来源店铺 003",
    platform: "LAZADA",
    status: "UNMAPPED",
  },
  {
    key: "shop-map-04",
    sourceShopName: "来源店铺 004",
    platform: "LAZADA",
    status: "UNMAPPED",
  },
];
